# Generated by Django 5.0.6 on 2025-10-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('engagement', models.CharField(blank=True, max_length=255, null=True)),
                ('task_code', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('source_ids', models.JSONField(default=list)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_utc', models.DateTimeField()),
                ('app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bundle_id', models.CharField(blank=True, max_length=255, null=True)),
                ('window_title', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ts_utc'], name='tracker_raw_ts_utc_db081d_idx'), models.Index(fields=['user', 'hostname'], name='tracker_raw_user_af82fa_idx')],
            },
        ),
    ]
