# Generated by Django 5.0.6 on 2025-10-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_client_project_block_rule_suggestion_task_block_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='window_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
