# Generated by Django 5.0.6 on 2025-10-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0003_block_window_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='ai_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='block',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='ai_extracted_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AIProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(max_length=50)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('model_used', models.CharField(max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TimecardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('date', models.DateField(db_index=True)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('activities_summary', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('needs_review', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('block_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.client')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.project')),
            ],
            options={
                'ordering': ['-date', '-total_hours'],
                'indexes': [models.Index(fields=['org', 'user', 'date'], name='tracker_tim_org_id_9547de_idx'), models.Index(fields=['status'], name='tracker_tim_status_903547_idx')],
            },
        ),
    ]
