# Generated by Django 5.0.6 on 2025-10-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0004_block_ai_category_block_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timecardentry',
            unique_together={('org', 'user', 'date', 'client')},
        ),
    ]
