# Generated by Django 5.0.6 on 2025-10-23 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0005_alter_timecardentry_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITrainingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(help_text='The text that was classified')),
                ('correct_categories', models.JSONField(default=dict, help_text='Category -> hours')),
                ('original_prediction', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correct_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_examples', to='tracker.client')),
                ('correct_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_examples', to='tracker.project')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_examples', to='auth.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text="Your company name (e.g., 'PredictorEdge')", max_length=200)),
                ('industry', models.CharField(blank=True, help_text='Industry/sector', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of what your company does')),
                ('internal_keywords', models.JSONField(default=list, help_text="Keywords that indicate internal work (e.g., ['admin', 'internal', 'team meeting'])")),
                ('default_internal_project', models.CharField(blank=True, help_text='Default project name for internal work', max_length=200)),
                ('custom_instructions', models.TextField(blank=True, help_text="Custom instructions for the AI classifier (e.g., 'Anything mentioning standup is internal')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='auth.group')),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
            },
        ),
        migrations.CreateModel(
            name='KnownEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('client', 'Client'), ('project', 'Project'), ('category', 'Category'), ('person', 'Person')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.JSONField(default=list, help_text="Alternative names or keywords (e.g., ['ACME', 'Acme Corp', 'acme.com'])")),
                ('description', models.TextField(blank=True)),
                ('is_internal', models.BooleanField(default=False, help_text='Mark as internal (not a real client)')),
                ('confidence_boost', models.FloatField(default=0.0, help_text='Boost confidence when this entity is detected (-1.0 to 1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_entities', to='auth.group')),
                ('parent_client', models.ForeignKey(blank=True, help_text='For projects, link to parent client', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.client')),
            ],
            options={
                'ordering': ['entity_type', 'name'],
                'unique_together': {('org', 'entity_type', 'name')},
            },
        ),
    ]
