# Generated by Django 5.0.6 on 2025-10-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0006_aitrainingexample_organizationsettings_knownentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='attendees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='block',
            name='category_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='block',
            name='day',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='block',
            name='minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['org', 'user', 'day'], name='tracker_blo_org_id_dd259c_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['org', 'start'], name='tracker_blo_org_id_da1583_idx'),
        ),
    ]
