# Generated by Django 5.0.6 on 2025-10-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_block_hints_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawevent',
            name='ctx',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='block',
            name='hints',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
