# Generated by Django 5.0.6 on 2025-10-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0011_remove_dupes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['org', 'name'], name='tracker_cli_org_id_62bd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['org', 'client', 'name'], name='tracker_pro_org_id_0a53bc_idx'),
        ),
    ]
