# Generated by Django 5.0.6 on 2025-10-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_client_tracker_cli_org_id_62bd6e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=80)),
                ('hostname', models.CharField(db_index=True, max_length=120)),
                ('last_seen', models.DateTimeField()),
                ('last_app', models.CharField(blank=True, max_length=120)),
                ('last_window_title', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'unique_together': {('user', 'hostname')},
            },
        ),
    ]
