# Generated by Django 5.0.6 on 2025-10-29 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0013_agentsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('stop', models.BooleanField(db_index=True, default=False)),
                ('stop_until', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='uniq_client_org_lowername',
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='uniq_project_org_client_lowername',
        ),
        migrations.RenameIndex(
            model_name='block',
            new_name='tracker_blo_org_id_8f50cf_idx',
            old_name='tracker_blo_org_id_dd259c_idx',
        ),
        migrations.RenameIndex(
            model_name='rawevent',
            new_name='tracker_raw_user_id_64ca3c_idx',
            old_name='tracker_raw_user_af82fa_idx',
        ),
        migrations.RenameIndex(
            model_name='timecardentry',
            new_name='tracker_tim_org_id_4628b2_idx',
            old_name='tracker_tim_org_id_9547de_idx',
        ),
        migrations.AddField(
            model_name='agentsession',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='last_seen',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='aiprocessinglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aitrainingexample',
            name='correct_categories',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='aitrainingexample',
            name='text_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knownentity',
            name='aliases',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='knownentity',
            name='confidence_boost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='knownentity',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='knownentity',
            name='parent_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.client'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='custom_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='default_internal_project',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='industry',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='internal_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='rawevent',
            name='hostname',
            field=models.CharField(blank=True, default='unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rawevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestedblock',
            name='hostname',
            field=models.CharField(blank=True, default='unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='suggestedblock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timecardentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('org', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('org', 'client', 'name')},
        ),
        migrations.AddField(
            model_name='agentcontrol',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='agentcontrol',
            unique_together={('user', 'host')},
        ),
    ]
