# Generated by Django 5.0.6 on 2025-10-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_agentcontrol_remove_client_uniq_client_org_lowername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsession',
            name='user',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
