# Generated by Django 5.0.6 on 2025-10-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_agentsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='last_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
