# Generated by Django 5.0.6 on 2025-10-31 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0017_agentsession_last_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('match_type', models.CharField(choices=[('domain', 'Domain (email domain or URL)'), ('path', 'File path segment'), ('keyword', 'Keyword'), ('regex', 'Regex')], max_length=20)),
                ('pattern', models.TextField()),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_category', models.CharField(max_length=100)),
                ('match_type', models.CharField(choices=[('bundle', 'App Bundle ID'), ('keyword', 'Keyword'), ('regex', 'Regex'), ('path_ext', 'File Extension')], max_length=20)),
                ('pattern', models.TextField()),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='suggestedblock',
            name='user',
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['org', 'client'], name='tracker_blo_org_id_3c481f_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['org', 'project'], name='tracker_blo_org_id_a6c567_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['org', 'task'], name='tracker_blo_org_id_5d5b92_idx'),
        ),
        migrations.AddIndex(
            model_name='rawevent',
            index=models.Index(fields=['user', 'ts_utc'], name='tracker_raw_user_id_62ce03_idx'),
        ),
        migrations.AddField(
            model_name='classificationoverride',
            name='raw_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='tracker.rawevent'),
        ),
        migrations.AddField(
            model_name='clientpattern',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_patterns', to='auth.group'),
        ),
        migrations.AddField(
            model_name='taskpattern',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_patterns', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='SuggestedBlock',
        ),
        migrations.AddIndex(
            model_name='classificationoverride',
            index=models.Index(fields=['raw_event'], name='tracker_cla_raw_eve_72b087_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpattern',
            index=models.Index(fields=['org', 'match_type'], name='tracker_cli_org_id_351730_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpattern',
            index=models.Index(fields=['org', 'client_name'], name='tracker_cli_org_id_72c791_idx'),
        ),
        migrations.AddIndex(
            model_name='taskpattern',
            index=models.Index(fields=['org', 'match_type'], name='tracker_tas_org_id_1ccd15_idx'),
        ),
        migrations.AddIndex(
            model_name='taskpattern',
            index=models.Index(fields=['org', 'task_category'], name='tracker_tas_org_id_9de4af_idx'),
        ),
    ]
