# Generated by Django 5.0.6 on 2025-11-05 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_agentdevice_agentpaircode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdevice',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agentdevice',
            name='device_id',
            field=models.CharField(db_index=True, help_text='Stable UUID generated by the agent and stored locally', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='agentdevice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agentdevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agentdevice',
            index=models.Index(fields=['user', 'hostname'], name='tracker_age_user_id_2568c5_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdevice',
            index=models.Index(fields=['is_active', 'last_seen_at'], name='tracker_age_is_acti_a17a5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentdevice',
            constraint=models.CheckConstraint(check=models.Q(('is_active', False), ('api_key__isnull', False), _connector='OR'), name='api_key_required_when_active'),
        ),
    ]
