# Generated by Django 5.0.6 on 2025-11-06 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_alter_agentdevice_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rawevent',
            name='tracker_raw_user_id_62ce03_idx',
        ),
        migrations.AddField(
            model_name='block',
            name='device_id',
            field=models.CharField(db_index=True, default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='rawevent',
            name='device_id',
            field=models.CharField(db_index=True, default='unknown', max_length=64),
        ),
        migrations.AddIndex(
            model_name='rawevent',
            index=models.Index(fields=['user', 'device_id', 'ts_utc'], name='tracker_raw_user_id_e94a88_idx'),
        ),
    ]
