# Generated by Django 5.0.6 on 2025-11-11 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_remove_rawevent_tracker_raw_user_id_62ce03_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(db_index=True, default=0, help_text='AgentDevice.id for per-device client selection (0 = all devices)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the user switched to this client')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this selection was confirmed/updated')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_selections', to='tracker.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Current Client Selection',
                'verbose_name_plural': 'Current Client Selections',
                'indexes': [models.Index(fields=['user', 'device_id'], name='tracker_cur_user_id_17d1e2_idx'), models.Index(fields=['user', 'updated_at'], name='tracker_cur_user_id_e16f76_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
