# Generated by Django 5.0.6 on 2025-11-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_currentclient'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='tracker_cli_org_id_62bd6e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, default='', help_text="Short code like 'ACME' or 'JOHN'", max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
