# Generated by Django 5.0.6 on 2025-11-11 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0024_remove_client_tracker_cli_org_id_62bd6e_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('org', 'code')},
        ),
    ]
