# Generated by Django 5.0.6 on 2025-11-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_alter_client_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='app_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='block',
            name='bundle_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
