# Generated by Django 5.0.6 on 2025-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_block_app_name_block_bundle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawevent',
            name='current_client_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
