# Generated by Django 5.0.6 on 2025-11-14 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0027_rawevent_current_client_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('file_path', 'File Path Pattern'), ('time_of_day', 'Time of Day Pattern'), ('day_of_week', 'Day of Week Pattern'), ('app_sequence', 'Application Sequence'), ('tool_usage', 'Tool Usage Pattern'), ('client_folder', 'Client Folder Mapping')], db_index=True, max_length=30)),
                ('pattern_key', models.CharField(db_index=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('total_predictions', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('metadata', models.JSONField(default=dict)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_confirmed', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.client')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_userworkpattern',
                'indexes': [models.Index(fields=['user', 'pattern_type'], name='tracker_use_user_id_cbd070_idx'), models.Index(fields=['user', 'client'], name='tracker_use_user_id_6783c0_idx'), models.Index(fields=['confidence_score'], name='tracker_use_confide_7cc430_idx')],
                'unique_together': {('user', 'pattern_type', 'pattern_key')},
            },
        ),
    ]
