# Generated by Django 5.0.6 on 2025-11-14 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0028_userworkpattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['-start']},
        ),
        migrations.AddField(
            model_name='block',
            name='approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Approved for billing by user/manager'),
        ),
        migrations.AddField(
            model_name='block',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this block was approved', null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Who approved this block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='categorized_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this block was first categorized', null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='categorized_by',
            field=models.CharField(blank=True, choices=[('ai', 'AI Auto-Categorized'), ('manual', 'User Manual Entry'), ('correction', 'User Corrected AI'), ('import', 'Imported Data'), ('pattern', 'Learned Pattern')], db_index=True, help_text='Source of the categorization', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='is_categorized',
            field=models.BooleanField(db_index=True, default=False, help_text='True once categories are assigned - block becomes immutable'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['is_categorized', 'user', 'start'], name='tracker_blo_is_cate_eeaf68_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['categorized_by', 'org'], name='tracker_blo_categor_3c9948_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['approved', 'user', 'day'], name='tracker_blo_approve_044bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['approved', 'org', 'client'], name='tracker_blo_approve_e871f4_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['is_categorized', 'org', 'day'], name='tracker_blo_is_cate_b415b6_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['is_categorized', 'ai_processed_at'], name='tracker_blo_is_cate_d20665_idx'),
        ),
    ]
