# Generated by Django 5.0.6 on 2025-11-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracker', '0030_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=20)),
                ('is_billable', models.BooleanField(default=True)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='auth.group')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='task_type',
            field=models.ForeignKey(blank=True, help_text='Firm-wide activity type (Tax Prep, Research, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='tracker.tasktype'),
        ),
        migrations.AddIndex(
            model_name='tasktype',
            index=models.Index(fields=['org', 'is_active'], name='tracker_tas_org_id_5fdee8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktype',
            unique_together={('org', 'name')},
        ),
    ]
