# Generated by Django 5.0.6 on 2025-12-01 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_orgprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentregistration',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='aiprocessinglog',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='aitrainingexample',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_examples', to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='block',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='client',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='clientpattern',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_patterns', to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='knownentity',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_entities', to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='orginstalltoken',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='install_token', to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='task',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='taskpattern',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_patterns', to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='timecardentry',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.organization'),
        ),
        migrations.AlterField(
            model_name='userworkpattern',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.organization'),
        ),
    ]
