# Generated by Django 5.0.6 on 2025-12-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_alter_agentregistration_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
