# Generated by Django 5.0.6 on 2025-12-08 20:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_block_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='billing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated: (minutes/60) * billing_rate', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='billing_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate applied to this block', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='description_override',
            field=models.TextField(blank=True, default='', help_text='Custom description for invoice line item (overrides auto-generated)'),
        ),
        migrations.AddField(
            model_name='block',
            name='invoice_reference',
            field=models.CharField(blank=True, default='', help_text='Reference to external invoice (e.g., QBO invoice ID)', max_length=100),
        ),
        migrations.AddField(
            model_name='block',
            name='invoiced',
            field=models.BooleanField(db_index=True, default=False, help_text='Has this block been included in an invoice?'),
        ),
        migrations.AddField(
            model_name='block',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='is_billable',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this time is billable to client'),
        ),
        migrations.CreateModel(
            name='BillingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Hourly billing rate in dollars', max_digits=10)),
                ('effective_date', models.DateField(default=django.utils.timezone.now, help_text='Rate effective from this date')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_rates', to='tracker.client')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_rates', to='tracker.organization')),
                ('task_type', models.ForeignKey(blank=True, help_text='Optional: rate for specific task type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.tasktype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='BlockAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('categorize', 'Categorized'), ('approve', 'Approved'), ('reject', 'Rejected'), ('lock', 'Locked'), ('delete', 'Deleted')], max_length=20)),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tracker.block')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, help_text='Monday of the timesheet week')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_notes', models.TextField(blank=True, default='', help_text='Notes from employee on submission')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, default='')),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('billable_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('non_billable_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='tracker.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_timesheets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='timesheet',
            field=models.ForeignKey(blank=True, help_text='Weekly timesheet this block belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='tracker.timesheet'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['is_billable', 'org', 'client'], name='tracker_blo_is_bill_d4693d_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['timesheet', 'user'], name='tracker_blo_timeshe_421040_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['invoiced', 'approved', 'client'], name='tracker_blo_invoice_e62a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrate',
            index=models.Index(fields=['org', 'user', 'effective_date'], name='tracker_bil_org_id_1a5513_idx'),
        ),
        migrations.AddIndex(
            model_name='billingrate',
            index=models.Index(fields=['org', 'user', 'client'], name='tracker_bil_org_id_d9c2d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingrate',
            constraint=models.UniqueConstraint(fields=('org', 'user', 'client', 'task_type', 'effective_date'), name='unique_billing_rate'),
        ),
        migrations.AddIndex(
            model_name='blockauditlog',
            index=models.Index(fields=['block', 'timestamp'], name='tracker_blo_block_i_056cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='blockauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='tracker_blo_user_id_b03394_idx'),
        ),
        migrations.AddIndex(
            model_name='blockauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='tracker_blo_action_b639d7_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['org', 'status', 'week_start'], name='tracker_tim_org_id_2ec52f_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['org', 'user', 'status'], name='tracker_tim_org_id_dfac25_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['approved_by', 'status'], name='tracker_tim_approve_67cf88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('org', 'user', 'week_start')},
        ),
    ]
