# Generated by Django 5.0.6 on 2025-12-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_employeecostrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='auto_submitted',
            field=models.BooleanField(default=False, help_text='True if timesheet was automatically submitted by system (Tuesday auto-submit)'),
        ),
    ]
