# Generated by Django 5.0.6 on 2025-12-13 17:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_timesheet_auto_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='billing_rate_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), help_text='Default hourly billing rate', max_digits=10),
        ),
    ]
