# Generated by Django 5.0.6 on 2026-01-06 20:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0040_alter_organization_billing_rate_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cost_rate_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='Default hourly employee cost (for margin calculations)', max_digits=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='billing_rate_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), help_text='Default hourly billing rate charged to clients', max_digits=10),
        ),
    ]
