# Generated by Django 5.0.6 on 2026-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_organization_cost_rate_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='seat_count',
            field=models.IntegerField(default=1, help_text='Number of paid seats'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('none', 'No Plan'), ('professional', 'Professional'), ('executive', 'Executive')], default='none', max_length=20),
        ),
    ]
