# Generated by Django 5.0.6 on 2026-01-13 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_organization_seat_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='visibility',
            field=models.CharField(choices=[('all', 'All Team Members'), ('assigned', 'Assigned Only'), ('confidential', 'Confidential')], default='all', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Engagement Lead'), ('manager', 'Manager'), ('staff', 'Staff'), ('reviewer', 'Reviewer')], default='staff', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tracker.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='tracker.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'client'], name='tracker_cli_user_id_df764b_idx'), models.Index(fields=['organization', 'user'], name='tracker_cli_organiz_bc1c52_idx')],
                'unique_together': {('client', 'user')},
            },
        ),
    ]
