# Generated by Django 5.0.6 on 2026-01-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0043_client_visibility_clientassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='visibility',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('assigned', 'Assigned'), ('confidential', 'Confidential')], default='all', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientassignment',
            name='role',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('manager', 'Manager'), ('lead', 'Engagement Lead'), ('reviewer', 'Reviewer')], max_length=20, null=True),
        ),
    ]
