# Generated by Django 5.0.6 on 2026-01-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0045_clientrequest_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='imported_from',
            field=models.CharField(blank=True, choices=[('', 'Manual'), ('quickbooks', 'QuickBooks'), ('xero', 'Xero')], default='', help_text='Integration source this client was imported from', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='quickbooks_id',
            field=models.CharField(blank=True, db_index=True, help_text='QuickBooks Customer ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='xero_id',
            field=models.CharField(blank=True, db_index=True, help_text='Xero Contact ID', max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('quickbooks_id__isnull', False)), fields=('org', 'quickbooks_id'), name='unique_quickbooks_client'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('xero_id__isnull', False)), fields=('org', 'xero_id'), name='unique_xero_client'),
        ),
    ]
