# Generated by Django 5.0.6 on 2026-01-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0046_client_imported_from_client_quickbooks_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassignment',
            name='role',
            field=models.CharField(blank=True, choices=[('Partner', 'Partner'), ('Manager', 'Manager'), ('Senior', 'Senior'), ('Staff', 'Staff'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
    ]
