# Generated by Django 5.0.6 on 2026-01-19 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0047_alter_clientassignment_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawevent',
            name='block',
            field=models.ForeignKey(blank=True, help_text='The block this event was compacted into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_events', to='tracker.block'),
        ),
    ]
