# Generated by Django 5.0.6 on 2026-01-25 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0049_alter_billingrate_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(db_index=True, max_length=50)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('app_version', models.CharField(max_length=20)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['error_type', 'created_at'], name='tracker_age_error_t_62deb7_idx'), models.Index(fields=['device_id', 'created_at'], name='tracker_age_device__8e7d1d_idx')],
            },
        ),
    ]
