# Generated by Django 5.0.6 on 2026-01-25 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0050_agenterror'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenterror',
            name='client_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenterror',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agenterror',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_errors', to='tracker.organization'),
        ),
        migrations.AddField(
            model_name='agenterror',
            name='os_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agenterror',
            name='python_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agenterror',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenterror',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agenterror',
            name='app_version',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='agenterror',
            name='hostname',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agenterror',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_errors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agenterror',
            index=models.Index(fields=['user', 'created_at'], name='tracker_age_user_id_a2cdc4_idx'),
        ),
        migrations.AddIndex(
            model_name='agenterror',
            index=models.Index(fields=['resolved', 'created_at'], name='tracker_age_resolve_07ee4e_idx'),
        ),
        migrations.AddIndex(
            model_name='agenterror',
            index=models.Index(fields=['app_version', 'created_at'], name='tracker_age_app_ver_d105bb_idx'),
        ),
    ]
