# Generated by Django 5.0.6 on 2026-01-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0051_agenterror_client_timestamp_agenterror_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='industry_type',
            field=models.CharField(choices=[('cpa', 'CPA / Accounting Firm'), ('ai_consulting', 'AI / Technology Consulting'), ('marketing', 'Marketing / Creative Agency'), ('legal', 'Law Firm'), ('general', 'General Professional Services')], default='general', help_text='Industry type determines available categories', max_length=50),
        ),
    ]
