# Generated by Django 5.0.6 on 2026-02-03 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0052_organization_industry_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('budget_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='tracker.client')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_budgets', to='tracker.organization')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hours_billed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('client_code', models.CharField(blank=True, max_length=50)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('quickbooks', 'QuickBooks'), ('xero', 'Xero'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tracker.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tracker.organization')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
                'indexes': [models.Index(fields=['org', 'invoice_date'], name='tracker_inv_org_id_040249_idx'), models.Index(fields=['org', 'client'], name='tracker_inv_org_id_b70842_idx'), models.Index(fields=['client_code'], name='tracker_inv_client__d89ed8_idx')],
                'unique_together': {('org', 'invoice_number')},
            },
        ),
    ]
