# Generated by Django 5.0.6 on 2026-02-04 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0053_clientbudget_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='slate', help_text='Color for UI display: slate, red, orange, amber, emerald, blue, purple, pink', max_length=20)),
                ('icon', models.CharField(default='folder', help_text='Icon name: folder, briefcase, users, star, tag', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clients', models.ManyToManyField(blank=True, related_name='groups', to='tracker.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_groups', to=settings.AUTH_USER_MODEL)),
                ('default_assignees', models.ManyToManyField(blank=True, help_text='Users automatically assigned when clients are added to this group', related_name='default_group_assignments', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_groups', to='tracker.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('org', 'name')},
            },
        ),
    ]
