# Generated by Django 5.0.6 on 2026-02-04 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0054_clientgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_timesheet_reminders', models.BooleanField(default=True, help_text='Receive daily email reminders for unreviewed timesheets')),
                ('email_weekly_summary', models.BooleanField(default=True, help_text='Receive weekly time summary emails')),
                ('email_approval_notifications', models.BooleanField(default=True, help_text='Receive emails when timesheets are approved/rejected')),
                ('desktop_notifications', models.BooleanField(default=True, help_text='Show desktop notifications from the agent')),
                ('reminder_time', models.CharField(default='09:00', help_text='Preferred time for reminders (HH:MM)', max_length=5)),
                ('last_timesheet_reminder_dismissed', models.CharField(blank=True, help_text='Date of last dismissed reminder (YYYY-MM-DD)', max_length=10, null=True)),
                ('default_view', models.CharField(choices=[('timesheet', 'My Timesheet'), ('dashboard', 'Dashboard'), ('reports', 'Reports')], default='timesheet', max_length=20)),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
