# Generated by Django 5.0.6 on 2026-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0055_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='email_timesheet_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
