# Generated by Django 5.0.6 on 2026-02-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0056_userpreference_email_timesheet_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkpattern',
            name='pattern_type',
            field=models.CharField(choices=[('app', 'Application Pattern'), ('domain', 'URL Domain Pattern'), ('window_title_prefix', 'Window Title Pattern'), ('file_path', 'File Path Pattern'), ('client_folder', 'Client Folder Mapping'), ('category_folder', 'Category Folder Pattern'), ('time_slot', 'Time Slot Pattern'), ('app_sequence', 'Application Sequence')], db_index=True, max_length=30),
        ),
    ]
