# Generated by Django 5.0.6 on 2026-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0058_add_integration_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='quickbooks_employee_id',
            field=models.CharField(blank=True, help_text='QuickBooks Employee ID for time entry push', max_length=50, null=True),
        ),
    ]
