# Generated by Django 5.0.6 on 2026-02-18
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tracker', '0059_organizationmembership_quickbooks_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='email_timesheet_reminder',
        ),
    ]