# Generated by Django 5.0.6 on 2026-02-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0060_remove_duplicate_email_timesheet_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='email_timesheet_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
