# Generated by Django 5.0.6 on 2026-02-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0061_userpreference_email_timesheet_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='email_timesheet_reminder',
        ),
    ]
