# Generated by Django 5.0.6 on 2026-02-23 21:38

import django.db.models.deletion
import tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0062_remove_userpreference_email_timesheet_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdevice',
            name='auto_matched',
            field=models.BooleanField(default=False, help_text='True if user was auto-matched by email, False if manually selected'),
        ),
        migrations.CreateModel(
            name='OrgDeploymentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=tracker.models.generate_org_token, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_devices', models.PositiveIntegerField(blank=True, help_text='Max devices that can claim this token. Null = unlimited.', null=True)),
                ('devices_claimed', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deployment_tokens', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_tokens', to='tracker.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='claimed_via_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_devices', to='tracker.orgdeploymenttoken'),
        ),
    ]
