# Generated by Django 5.0.6 on 2026-02-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0063_agentdevice_auto_matched_orgdeploymenttoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdevice',
            name='os_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
