# Generated by Django 5.0.6 on 2026-02-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0064_agentdevice_os_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_submit_timesheets',
            field=models.BooleanField(default=False, help_text='Auto-submit draft timesheets on Tuesday 9am'),
        ),
    ]
