# Generated by Django 5.0.6 on 2026-02-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0065_organization_auto_submit_timesheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_grace_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
