# Generated by Django 5.0.6 on 2026-02-27 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0066_organization_payment_grace_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft - Data collected, not yet imported'), ('imported', 'Imported - Users/clients/devices loaded'), ('msi_built', 'MSI Built - Installer ready for IT'), ('deployed', 'Deployed - MSI pushed to machines'), ('active', 'Active - Devices pairing'), ('complete', 'Complete - All devices paired')], default='draft', max_length=20)),
                ('total_users', models.IntegerField(default=0)),
                ('total_devices', models.IntegerField(default=0)),
                ('total_clients', models.IntegerField(default=0)),
                ('devices_paired', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_batches_created', to=settings.AUTH_USER_MODEL)),
                ('deployment_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_batch', to='tracker.orgdeploymenttoken')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_batches', to='tracker.organization')),
            ],
            options={
                'verbose_name': 'Onboarding Batch',
                'verbose_name_plural': 'Onboarding Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceProvisioningMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_hostname', models.CharField(db_index=True, help_text='Machine hostname from Intune/AD export (e.g., FIRM-PC-101)', max_length=255)),
                ('windows_username', models.CharField(blank=True, db_index=True, default='', help_text='DOMAIN\\username from AD (e.g., FIRMNAME\\jsmith)', max_length=255)),
                ('email', models.EmailField(db_index=True, help_text='User email to pair this device to', max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20)),
                ('billing_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly billing rate for this user', max_digits=10, null=True)),
                ('cost_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly cost rate for this user', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - Waiting for agent to connect'), ('paired', 'Paired - Device matched and linked'), ('failed', 'Failed - Agent connected but match failed'), ('manual', 'Manual - Fell back to manual pairing')], db_index=True, default='pending', max_length=20)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('match_method', models.CharField(blank=True, default='', help_text='How the match was made: hostname, windows_username, or manual', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_maps', to='tracker.organization')),
                ('paired_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioning_map', to='tracker.agentdevice')),
                ('paired_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_devices', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_maps', to='tracker.onboardingbatch')),
            ],
            options={
                'verbose_name': 'Device Provisioning Map',
                'verbose_name_plural': 'Device Provisioning Maps',
                'indexes': [models.Index(fields=['organization', 'machine_hostname'], name='tracker_dev_organiz_29ef6b_idx'), models.Index(fields=['organization', 'windows_username'], name='tracker_dev_organiz_db53b9_idx'), models.Index(fields=['organization', 'email'], name='tracker_dev_organiz_16c384_idx'), models.Index(fields=['status', 'organization'], name='tracker_dev_status_0adfdc_idx')],
                'unique_together': {('organization', 'machine_hostname')},
            },
        ),
    ]
