# Generated by Django 5.0.6 on 2026-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0067_onboardingbatch_deviceprovisioningmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ai_sensitivity',
            field=models.PositiveSmallIntegerField(default=50, help_text='Controls how aggressively the desktop agent matches window titles to clients (0 = conservative, 50 = balanced, 100 = aggressive). Admin-only setting.'),
        ),
    ]
