# Generated by Django 5.0.6 on 2026-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0069_integration_last_synced_at_invoiceconflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('voided', 'Voided'), ('overdue', 'Overdue')], default='sent', max_length=20),
        ),
    ]
