# Generated by Django 5.0.6 on 2026-03-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0070_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='quickbooks_realm_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
