# Generated by Django 5.0.6 on 2026-03-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0071_client_quickbooks_realm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='xero_tenant_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
