# Generated by Django 5.0.6 on 2026-03-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0073_blocks_need_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='needs_review',
        ),
        migrations.RemoveField(
            model_name='block',
            name='review_reason',
        ),
    ]
