# Generated by Django 5.0.6 on 2026-03-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0075_block_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='aliases',
            field=models.JSONField(blank=True, default=list, help_text='Alternative names/abbreviations for AI client matching'),
        ),
    ]
