# Generated by Django 5.0.6 on 2026-03-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0076_client_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpattern',
            name='match_type',
            field=models.CharField(choices=[('domain', 'Domain (email domain or URL)'), ('path', 'File path segment'), ('keyword', 'Keyword'), ('regex', 'Regex'), ('app', 'App name'), ('title', 'Window title')], max_length=20),
        ),
    ]
