# Generated by Django 5.0.6 on 2026-03-23 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0077_alter_clientpattern_match_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdevice',
            name='log_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_device_id', models.CharField(db_index=True, max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('platform', models.CharField(default='unknown', max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('trigger', models.CharField(default='scheduled', max_length=50)),
                ('log_text', models.TextField()),
                ('line_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.agentdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
