# Generated by Django 5.0.6 on 2026-03-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0078_agentdevice_log_requested_agentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdevice',
            name='restart_requested',
            field=models.BooleanField(default=False),
        ),
    ]
