# Generated by Django 5.0.6 on 2026-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0079_agentdevice_restart_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mouse_idle_pause_seconds',
            field=models.IntegerField(default=90),
        ),
    ]
