# Generated by Django 5.0.6 on 2026-04-03 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0080_organization_mouse_idle_pause_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('deterministic', 'Deterministic'), ('pattern', 'Pattern'), ('ai', 'AI'), ('manual', 'Manual'), ('error', 'Error')], max_length=20)),
                ('category_before', models.CharField(blank=True, max_length=100)),
                ('category_after', models.CharField(blank=True, max_length=100)),
                ('confidence_client', models.FloatField(default=0)),
                ('confidence_category', models.FloatField(default=0)),
                ('overall_confidence', models.FloatField(default=0)),
                ('matched_signals', models.JSONField(default=list)),
                ('corrected_by_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='tracker.block')),
                ('client_after', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracker.client')),
                ('client_before', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracker.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['block'], name='tracker_cla_block_i_c620dc_idx'), models.Index(fields=['source'], name='tracker_cla_source_a640ed_idx'), models.Index(fields=['created_at'], name='tracker_cla_created_a9f534_idx')],
            },
        ),
    ]
