# Generated by Django 5.0.6 on 2026-04-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0081_classificationaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='tax_return_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='taxpayer_id_hash',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='taxpayer_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='TaxpayerBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxpayer_id_hash', models.CharField(db_index=True, max_length=16)),
                ('display_name', models.CharField(max_length=120)),
                ('return_types_seen', models.JSONField(blank=True, default=list)),
                ('software', models.CharField(blank=True, default='', max_length=32)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxpayer_buckets', to='tracker.organization')),
            ],
            options={
                'db_table': 'tracker_taxpayer_bucket',
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='taxpayer_bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='tracker.taxpayerbucket'),
        ),
        migrations.AddConstraint(
            model_name='taxpayerbucket',
            constraint=models.UniqueConstraint(fields=('org', 'taxpayer_id_hash'), name='unique_taxpayer_per_org'),
        ),
    ]
