# Generated by Django 5.0.6 on 2026-04-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0082_block_tax_return_type_block_taxpayer_id_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdevice',
            name='kill_requested',
            field=models.BooleanField(default=False),
        ),
    ]
