# Generated by Django 5.0.6 on 2026-04-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0083_agentdevice_kill_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
