# Generated by Django 5.0.6 on 2026-04-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0085_fk_cascade_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mouse_idle_pause_seconds',
            field=models.IntegerField(default=600),
        ),
    ]
