# Generated by Django 5.0.6 on 2026-04-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0086_alter_organization_mouse_idle_pause_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_meeting',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this block represents a detected video/audio meeting'),
        ),
        migrations.AddField(
            model_name='block',
            name='meeting_app',
            field=models.CharField(blank=True, help_text='Canonical meeting app key: zoom, teams, meet, webex, facetime, slack, discord', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='meeting_detection_confidence',
            field=models.FloatField(blank=True, help_text='0.0-1.0 confidence score from detector (signal count / 3)', null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='meeting_detection_sources',
            field=models.JSONField(blank=True, help_text="List of detection sources: ['audio','camera','process','title']", null=True),
        ),
    ]
