# Generated by Django 5.0.6 on 2026-04-21 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0087_block_is_meeting_block_meeting_app_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('exe', 'Exact Process Name (exe)'), ('exe_family', 'App Family (matches multiple versions)'), ('title_contains', 'Title Contains (case-insensitive)'), ('title_regex', 'Title Matches Regex'), ('file_path_contains', 'File Path Contains')], help_text='What part of the window event this rule matches on.', max_length=32)),
                ('match_value', models.CharField(help_text="The value to match. For exe_family, use a short key like 'taxwise', 'ultratax', 'lacerte' — agent maps these to exe name prefixes.", max_length=255)),
                ('action', models.CharField(choices=[('route_to_client', 'Route Tracking to a Specific Client'), ('never_switch_away', 'Stay on Currently Selected Client'), ('suppress', 'Ignore This Window Entirely')], default='route_to_client', max_length=32)),
                ('priority', models.IntegerField(default=100, help_text='Higher priority rules evaluated first. Defaults:\n  500 = org-specific hard rules (tax software, etc.)\n  300 = default baseline rules shipped to all orgs\n  100 = user-created soft rules')),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, help_text='Human-readable explanation; shown in admin UI.', max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='True for rules seeded from default_routing_rules.json. Firm admins can disable but not delete these; MavOps can push updates to them globally.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fire_count', models.IntegerField(default=0)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules_created', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='tracker.organization')),
                ('target_client', models.ForeignKey(blank=True, help_text="Required when action='route_to_client'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='tracker.client')),
            ],
            options={
                'ordering': ['-priority', 'id'],
                'indexes': [models.Index(fields=['org', 'enabled', '-priority'], name='tracker_org_org_id_cd92ee_idx')],
            },
        ),
    ]
