# Generated by Django 5.0.6 on 2026-04-27 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0088_orgroutingrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleFireLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_version', models.IntegerField(default=1, help_text="Snapshot of the rule version at fire time. Lets us tell if a rule's behavior changed since this fire.")),
                ('engine', models.CharField(choices=[('agent', 'Desktop Agent'), ('classifier', 'Block Classifier'), ('compaction', 'Compaction'), ('post_save', 'Post-Save Signal')], db_index=True, max_length=20)),
                ('context', models.JSONField(blank=True, default=dict, help_text='What the engine saw when matching: window title, exe, file_path, duration, etc. Useful for debugging and LLM #3 explanations.')),
                ('outcome', models.JSONField(blank=True, default=dict, help_text='What the rule did: assigned category, switched client, flagged, marked non-billable, etc.')),
                ('fired_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('block', models.ForeignKey(blank=True, help_text='The block, if applicable. Null for agent-stage fires.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_fires', to='tracker.block')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_fire_logs', to='tracker.organization')),
                ('rule', models.ForeignKey(help_text='The rule that fired.', on_delete=django.db.models.deletion.CASCADE, related_name='fire_logs', to='tracker.orgroutingrule')),
            ],
            options={
                'ordering': ['-fired_at'],
                'indexes': [models.Index(fields=['org', '-fired_at'], name='tracker_rul_org_id_7206fa_idx'), models.Index(fields=['rule', '-fired_at'], name='tracker_rul_rule_id_c36eb5_idx'), models.Index(fields=['block', '-fired_at'], name='tracker_rul_block_i_5c10c6_idx'), models.Index(fields=['engine', '-fired_at'], name='tracker_rul_engine_3e9a20_idx')],
            },
        ),
    ]
