# Generated by Django 5.0.6 on 2026-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0089_rulefirelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgroutingrule',
            name='category',
            field=models.CharField(choices=[('routing', 'Routing'), ('categorization', 'Categorization'), ('billing', 'Billing'), ('flagging', 'Flagging')], default='routing', help_text='What kind of rule this is — drives which engine evaluates it.', max_length=20),
        ),
        migrations.AddField(
            model_name='orgroutingrule',
            name='flag_reason',
            field=models.CharField(blank=True, default='', help_text='For flagging rules: human-readable reason shown to reviewers.', max_length=200),
        ),
        migrations.AddField(
            model_name='orgroutingrule',
            name='runs_at',
            field=models.CharField(choices=[('agent', 'Agent (live, on-device)'), ('classifier', 'Classifier (server, real-time)'), ('compaction', 'Compaction (server, hourly)'), ('post_save', 'Post-save (server, after write)')], default='agent', help_text='Which engine stage evaluates this rule.', max_length=20),
        ),
        migrations.AddField(
            model_name='orgroutingrule',
            name='target_category',
            field=models.CharField(blank=True, default='', help_text='For categorization rules: the category name to assign.', max_length=100),
        ),
        migrations.AddField(
            model_name='orgroutingrule',
            name='threshold_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='For flagging/billing rules: minutes threshold (e.g. flag blocks > 240 min).', null=True),
        ),
    ]
