# Generated by Django 5.0.6 on 2026-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0090_orgroutingrule_category_orgroutingrule_flag_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgroutingrule',
            name='action',
            field=models.CharField(choices=[('route_to_client', 'Route Tracking to a Specific Client'), ('never_switch_away', 'Stay on Currently Selected Client'), ('suppress', 'Ignore This Window Entirely'), ('assign_category', 'Assign Category'), ('mark_non_billable', 'Mark Non-Billable'), ('cap_duration_at', 'Cap Duration At'), ('flag_for_review', 'Flag For Review')], default='route_to_client', max_length=32),
        ),
    ]
