# Generated by Django 5.0.6 on 2026-05-01 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0091_alter_orgroutingrule_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('microsoft', 'Microsoft Graph (Outlook)')], max_length=20)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('meeting_url', models.TextField(blank=True, default='', help_text='Zoom/Teams/Meet URL extracted from event description or location.')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('extraction_confidence', models.FloatField(default=0.0)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='MailSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Gmail'), ('microsoft', 'Microsoft Graph')], max_length=20)),
                ('external_id', models.CharField(db_index=True, help_text='Provider message ID, used for dedup and idempotent sync.', max_length=255)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('direction', models.CharField(choices=[('in', 'Received'), ('out', 'Sent')], max_length=10)),
                ('other_party_domain', models.CharField(db_index=True, help_text="Domain of the OTHER party. Inbound: sender's. Outbound: dominant recipient's.", max_length=120)),
                ('subject_extract', models.CharField(blank=True, default='', help_text='Subject text, ONLY stored if a client was successfully extracted from it.', max_length=255)),
                ('is_inbox', models.BooleanField(default=False)),
                ('has_attachment', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('microsoft_calendar', 'Microsoft Calendar (Graph)'), ('gmail', 'Gmail (metadata only)'), ('microsoft_mail', 'Microsoft Mail (metadata only)')], max_length=30)),
                ('is_connected', models.BooleanField(default=False)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('sync_failure_count', models.IntegerField(default=0, help_text='Consecutive failed syncs. After 5, sync is paused until user re-auths.')),
                ('oauth_state', models.CharField(blank=True, default='', max_length=128)),
                ('provider_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='classification_state',
            field=models.CharField(choices=[('captured', 'Captured — no classification yet'), ('proposed', 'Proposed — classifier guessed, awaiting confirmation'), ('committed', 'Committed — confirmed, billable'), ('suppressed', 'Suppressed — not a real activity')], db_index=True, default='captured', help_text='Explicit state machine replacing the binary is_categorized flag.', max_length=20),
        ),
        migrations.AddField(
            model_name='block',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='proposed_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='block',
            name='proposed_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracker.client'),
        ),
        migrations.AddField(
            model_name='block',
            name='proposed_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='proposed_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='block',
            name='proposed_signals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='block',
            name='state_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='state_changed_by',
            field=models.CharField(blank=True, choices=[('classifier', 'Auto-classified by ClassificationService'), ('user', 'User confirmed via UI'), ('user_edit', 'User edited and committed'), ('admin_bulk', 'Admin bulk operation'), ('auto_commit_eod', 'End-of-day auto-commit'), ('rule', 'Org routing rule'), ('correction', 'User corrected after commit')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='disable_mail_integration',
            field=models.BooleanField(default=False, help_text='When True, mail integration is hidden from all users in this org and any existing connections are silently ignored. For firms with policies forbidding mail integration entirely.'),
        ),
        migrations.AlterField(
            model_name='orgroutingrule',
            name='action',
            field=models.CharField(choices=[('route_to_client', 'Route Tracking to a Specific Client'), ('never_switch_away', 'Stay on Currently Selected Client'), ('suppress', 'Ignore This Window Entirely'), ('assign_category', 'Assign Category'), ('mark_non_billable', 'Mark Non-Billable'), ('cap_duration_at', 'Cap Duration At'), ('flag_for_review', 'Flag For Review'), ('propose_only', 'Propose Only (always require review)')], default='route_to_client', max_length=32),
        ),
        migrations.AlterField(
            model_name='orgroutingrule',
            name='match_type',
            field=models.CharField(choices=[('exe', 'Exact Process Name (exe)'), ('exe_family', 'App Family (matches multiple versions)'), ('title_contains', 'Title Contains (case-insensitive)'), ('title_regex', 'Title Matches Regex'), ('file_path_contains', 'File Path Contains'), ('duration_gt', 'Block Duration Greater Than (minutes)'), ('inside_meeting', 'Block Is Inside a Meeting'), ('idle_gt', 'Idle Duration Greater Than (minutes)')], help_text='What part of the window event this rule matches on.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['classification_state', 'user', 'day'], name='tracker_blo_classif_0bd649_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['org', 'classification_state'], name='tracker_blo_org_id_fe3c61_idx'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='extracted_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='tracker.client'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='tracker.organization'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailsignal',
            name='extracted_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_signals', to='tracker.client'),
        ),
        migrations.AddField(
            model_name='mailsignal',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_signals', to='tracker.organization'),
        ),
        migrations.AddField(
            model_name='mailsignal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_integrations', to='tracker.organization'),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'start', 'end'], name='tracker_cal_user_id_f7fbc8_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['org', 'start'], name='tracker_cal_org_id_ed9b98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together={('user', 'provider', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='mailsignal',
            index=models.Index(fields=['user', 'occurred_at'], name='tracker_mai_user_id_fad9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='mailsignal',
            index=models.Index(fields=['user', 'other_party_domain'], name='tracker_mai_user_id_8be98b_idx'),
        ),
        migrations.AddIndex(
            model_name='mailsignal',
            index=models.Index(fields=['org', 'occurred_at'], name='tracker_mai_org_id_dfa390_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailsignal',
            unique_together={('user', 'provider', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='userintegration',
            index=models.Index(fields=['user', 'is_connected'], name='tracker_use_user_id_a768f2_idx'),
        ),
        migrations.AddIndex(
            model_name='userintegration',
            index=models.Index(fields=['org', 'provider'], name='tracker_use_org_id_e4b5d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userintegration',
            unique_together={('user', 'provider')},
        ),
    ]
