# Generated by Django 5.0.6 on 2026-05-07 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0096_remove_organization_use_classification_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='ai_disagreement_reasoning',
            field=models.TextField(blank=True, default='', help_text='AI evidence for the disagreement, shown in daily review tooltip'),
        ),
        migrations.AddField(
            model_name='block',
            name='ai_disagrees_with_agent',
            field=models.BooleanField(db_index=True, default=False, help_text='Stage 10 AI proposes a different client than the agent assigned'),
        ),
        migrations.AddField(
            model_name='block',
            name='ai_proposed_client',
            field=models.ForeignKey(blank=True, help_text='Client AI proposed when disagreeing with agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracker.client'),
        ),
        migrations.AddField(
            model_name='block',
            name='ai_proposed_confidence',
            field=models.FloatField(default=0.0, help_text='AI confidence in its proposed client (0.85-1.0)'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['user', 'day', 'ai_disagrees_with_agent'], name='tracker_blo_user_id_a6c1cc_idx'),
        ),
    ]
