# Generated by Django 5.0.6 on 2026-05-07 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0097_add_ai_disagreement_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='ai_disagreement_resolution',
            field=models.CharField(blank=True, choices=[('accepted', 'User accepted AI suggestion'), ('dismissed', 'User kept agent client'), ('changed_to_other', 'User picked a different client entirely')], help_text='How the user resolved the disagreement', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='ai_disagreement_resolved_at',
            field=models.DateTimeField(blank=True, help_text='When the user reviewed and dismissed/accepted the AI suggestion', null=True),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['ai_disagrees_with_agent', 'ai_disagreement_resolved_at'], name='tracker_blo_ai_disa_f9d371_idx'),
        ),
    ]
