# Generated by Django 5.0.6 on 2026-05-09 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0098_add_disagreement_resolution_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgCalendarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('title_contains', 'Title contains text'), ('title_pattern', 'Title regex pattern'), ('attendee_domain', 'External attendee email domain'), ('category_label', 'Outlook category label')], max_length=30)),
                ('match_value', models.CharField(help_text='Text to match', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100, help_text='Higher = checked first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_rules', to='tracker.organization')),
                ('target_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_rules', to='tracker.client')),
            ],
            options={
                'db_table': 'tracker_org_calendar_rule',
                'ordering': ['-priority', 'id'],
            },
        ),
    ]
