# Generated by Django 5.0.6 on 2026-05-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0099_orgcalendarrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='calendar_classification_enabled',
            field=models.BooleanField(default=False, help_text='Enable Stage 6 (calendar event overlap) in classifier'),
        ),
    ]
