# Generated by Django 5.0.6 on 2026-05-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0100_organization_calendar_classification_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mail_signal_retention_days',
            field=models.IntegerField(default=30, help_text='How long to retain MailSignal rows. Pruned nightly.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='mail_sync_interval_minutes',
            field=models.IntegerField(default=5, help_text='Per-org override for mail sync cadence. Default 5 min.'),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='mail_delta_link',
            field=models.TextField(blank=True, default='', help_text='Microsoft Graph delta link for /messages/delta. Empty = next sync is initial (last 30 days). Populated = next sync is incremental from this token.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='disable_mail_integration',
            field=models.BooleanField(default=False, help_text='Master switch — disables mail OAuth/sync/classifier for the whole org.'),
        ),
    ]
