# Generated by Django 5.0.6 on 2026-05-09 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0101_organization_mail_signal_retention_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mailsignal',
            index=models.Index(fields=['org', 'occurred_at', 'direction'], name='mailsig_org_time_dir_idx'),
        ),
    ]
