# Generated by Django 5.0.6 on 2026-05-09 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0102_mailsignal_mailsig_org_time_dir_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='mail_disagreement_reasoning',
            field=models.CharField(blank=True, default='', help_text='Human-readable explanation of why mail signal disagrees, shown in Daily Review.', max_length=500),
        ),
        migrations.AddField(
            model_name='block',
            name='mail_disagreement_resolution',
            field=models.CharField(blank=True, default='', help_text='How the user resolved the mail disagreement: accepted / dismissed / changed_to_other.', max_length=32),
        ),
        migrations.AddField(
            model_name='block',
            name='mail_disagreement_resolved_at',
            field=models.DateTimeField(blank=True, help_text='When the user resolved the mail disagreement; null = still pending review.', null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='mail_disagrees_with_agent',
            field=models.BooleanField(default=False, help_text='True when Stage 7 mail signal points to a different client than the block was attributed to.'),
        ),
        migrations.AddField(
            model_name='block',
            name='mail_proposed_client',
            field=models.ForeignKey(blank=True, help_text='Client that mail signals suggest, if different from block.client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_proposed_blocks', to='tracker.client'),
        ),
        migrations.AddField(
            model_name='block',
            name='mail_proposed_confidence',
            field=models.FloatField(blank=True, help_text='Stage 7 signal confidence for the mail-proposed client (0.0-1.0).', null=True),
        ),
    ]
