# Generated by Django 5.0.6 on 2026-05-12 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0104_rawevent_dual_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawevent',
            options={'ordering': ['start_ts']},
        ),
        migrations.RemoveIndex(
            model_name='rawevent',
            name='tracker_raw_ts_utc_db081d_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawevent',
            name='tracker_raw_user_id_e94a88_idx',
        ),
        migrations.RenameIndex(
            model_name='rawevent',
            new_name='tracker_raw_user_id_156e07_idx',
            old_name='rawevent_user_start_ts_idx',
        ),
        migrations.AddIndex(
            model_name='rawevent',
            index=models.Index(fields=['start_ts'], name='tracker_raw_start_t_a4c038_idx'),
        ),
        migrations.AddIndex(
            model_name='rawevent',
            index=models.Index(fields=['user', 'device_id', 'start_ts'], name='tracker_raw_user_id_f8ef2d_idx'),
        ),
    ]
