# Generated by Django 5.0.6 on 2026-05-14 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0109_integration_and_routing_rule_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clienttasktype',
            name='unique_client_task_type',
        ),
        migrations.RemoveConstraint(
            model_name='externalclientmapping',
            name='unique_ext_client_external_id',
        ),
        migrations.RemoveConstraint(
            model_name='externalclientmapping',
            name='unique_ext_client_internal',
        ),
        migrations.RemoveConstraint(
            model_name='externalstaffmapping',
            name='unique_ext_staff_external_id',
        ),
        migrations.RemoveConstraint(
            model_name='externalstaffmapping',
            name='unique_ext_staff_internal',
        ),
        migrations.RemoveConstraint(
            model_name='externaltasktypemapping',
            name='unique_ext_tt_external_id',
        ),
        migrations.RemoveConstraint(
            model_name='externaltasktypemapping',
            name='unique_ext_tt_internal',
        ),
        migrations.RemoveConstraint(
            model_name='tasktypeset',
            name='unique_tasktypeset_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='tasktypesetmember',
            name='unique_member_per_set',
        ),
        migrations.RemoveIndex(
            model_name='orgroutingrule',
            name='tracker_routing_src_idx',
        ),
        migrations.RenameIndex(
            model_name='clienttasktype',
            new_name='tracker_cli_client__b8225c_idx',
            old_name='tracker_cli_tt_allow_idx',
        ),
        migrations.RenameIndex(
            model_name='clienttasktype',
            new_name='tracker_cli_source_c56525_idx',
            old_name='tracker_cli_tt_src_idx',
        ),
        migrations.RenameIndex(
            model_name='externalclientmapping',
            new_name='tracker_ext_integra_5543ec_idx',
            old_name='tracker_ext_cli_ext_idx',
        ),
        migrations.RenameIndex(
            model_name='externalclientmapping',
            new_name='tracker_ext_client__e5005b_idx',
            old_name='tracker_ext_cli_int_idx',
        ),
        migrations.RenameIndex(
            model_name='externalstaffmapping',
            new_name='tracker_ext_integra_347c29_idx',
            old_name='tracker_ext_st_ext_idx',
        ),
        migrations.RenameIndex(
            model_name='externalstaffmapping',
            new_name='tracker_ext_user_id_01ca6e_idx',
            old_name='tracker_ext_st_int_idx',
        ),
        migrations.RenameIndex(
            model_name='externaltasktypemapping',
            new_name='tracker_ext_integra_ac3439_idx',
            old_name='tracker_ext_tt_ext_idx',
        ),
        migrations.RenameIndex(
            model_name='externaltasktypemapping',
            new_name='tracker_ext_task_ty_d19951_idx',
            old_name='tracker_ext_tt_int_idx',
        ),
        migrations.RenameIndex(
            model_name='tasktypeset',
            new_name='tracker_tas_org_id_41fc63_idx',
            old_name='tracker_tt_set_org_def_idx',
        ),
        migrations.RenameIndex(
            model_name='tasktypesetmember',
            new_name='tracker_tas_set_id_98a843_idx',
            old_name='tracker_tt_set_mem_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='default_task_type_set',
            field=models.ForeignKey(blank=True, help_text='Optional: overrides the org default TaskTypeSet for this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_using_as_default', to='tracker.tasktypeset'),
        ),
        migrations.AlterField(
            model_name='clienttasktype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externalclientmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externalstaffmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externaltasktypemapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='auto_create_internal_records',
            field=models.BooleanField(default=True, help_text='If True, sync auto-creates internal Client / TaskType records when it encounters external records with no mapping.'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('quickbooks', 'QuickBooks Online'), ('xero', 'Xero'), ('karbon', 'Karbon'), ('cch_axcess', 'CCH Axcess Practice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orgroutingrule',
            name='match_type',
            field=models.CharField(choices=[('exe', 'Exact Process Name (exe)'), ('exe_family', 'App Family (matches multiple versions)'), ('title_contains', 'Title Contains (case-insensitive)'), ('title_regex', 'Title Matches Regex'), ('file_path_contains', 'File Path Contains'), ('duration_gt', 'Block Duration Greater Than (minutes)'), ('inside_meeting', 'Block Is Inside a Meeting'), ('idle_gt', 'Idle Duration Greater Than (minutes)'), ('task_type_matrix', 'TaskType Matrix Rule')], help_text='What part of the window event this rule matches on.', max_length=32),
        ),
        migrations.AlterField(
            model_name='orgroutingrule',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('default_seed', 'Default Seed'), ('cch_axcess_sync', 'CCH Axcess Sync')], default='manual', help_text='How this rule was created. Synced rules are managed by the integration and should not be manually edited.', max_length=32),
        ),
        migrations.AlterField(
            model_name='tasktypeset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tasktypeset',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('cch_axcess_sync', 'CCH Axcess Sync'), ('seed', 'Seeded from default')], default='manual', help_text='Where this set came from. Synced sets are read-only in admin UI.', max_length=32),
        ),
        migrations.AlterField(
            model_name='tasktypesetmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='clienttasktype',
            unique_together={('client', 'task_type')},
        ),
        migrations.AlterUniqueTogether(
            name='externalclientmapping',
            unique_together={('integration', 'client'), ('integration', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='externalstaffmapping',
            unique_together={('integration', 'external_id'), ('integration', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='externaltasktypemapping',
            unique_together={('integration', 'external_id'), ('integration', 'task_type')},
        ),
        migrations.AlterUniqueTogether(
            name='tasktypeset',
            unique_together={('org', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tasktypesetmember',
            unique_together={('set', 'task_type')},
        ),
    ]
