# Generated by Django 5.0.6 on 2026-05-15 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0110_remove_clienttasktype_unique_client_task_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTaskTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(choices=[('seed', 'Seed (1:1 default from onboarding)'), ('manual', 'Manually configured'), ('cch_sync', 'CCH Axcess sync')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_task_type_mappings', to='tracker.organization')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='tracker.tasktype')),
            ],
            options={
                'verbose_name': 'Category → TaskType Mapping',
                'verbose_name_plural': 'Category → TaskType Mappings',
                'ordering': ['org_id', 'category'],
                'unique_together': {('org', 'category')},
            },
        ),
    ]
