# Generated by Django 5.0.6 on 2026-05-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0111_categorytasktypemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='calendar_disagreement_reasoning',
            field=models.CharField(blank=True, default='', help_text='Human-readable explanation of why calendar signal disagrees, shown in Daily Review.', max_length=500),
        ),
        migrations.AddField(
            model_name='block',
            name='calendar_disagreement_resolution',
            field=models.CharField(blank=True, default='', help_text='User action when resolving (e.g. accepted, dismissed, reassigned).', max_length=32),
        ),
        migrations.AddField(
            model_name='block',
            name='calendar_disagreement_resolved_at',
            field=models.DateTimeField(blank=True, help_text='When the user resolved the calendar disagreement; null = still pending review.', null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='calendar_disagreement_source',
            field=models.CharField(blank=True, choices=[('classifier', 'Classifier picked vs. calendar'), ('manual', 'User manually picked vs. calendar')], default='', help_text='Which attribution path produced the conflict. Drives Daily Review banner copy.', max_length=20),
        ),
        migrations.AddField(
            model_name='block',
            name='calendar_disagrees_with_agent',
            field=models.BooleanField(default=False, help_text='True when Stage 6 calendar event points to a different client than the block was attributed to.'),
        ),
        migrations.AddField(
            model_name='block',
            name='calendar_proposed_client',
            field=models.ForeignKey(blank=True, help_text='Client that the overlapping calendar event suggests, if different from block.client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_proposed_blocks', to='tracker.client'),
        ),
        migrations.AddField(
            model_name='block',
            name='calendar_proposed_confidence',
            field=models.FloatField(blank=True, help_text='Stage 6 signal confidence for the calendar-proposed client (0.55-0.85).', null=True),
        ),
    ]
