# Generated by Django 5.0.6 on 2026-05-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0113_analytics_v2'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientdailyrollup',
            new_name='tracker_v2__org_id_1ec4a4_idx',
            old_name='v2_cdr_org_day_idx',
        ),
        migrations.RenameIndex(
            model_name='clientdailyrollup',
            new_name='tracker_v2__org_id_437894_idx',
            old_name='v2_cdr_org_cli_day_idx',
        ),
        migrations.RenameIndex(
            model_name='savedview',
            new_name='tracker_v2__user_id_4d1203_idx',
            old_name='v2_sv_user_org_idx',
        ),
        migrations.RenameIndex(
            model_name='savedview',
            new_name='tracker_v2__org_id_2d13ea_idx',
            old_name='v2_sv_org_pinned_idx',
        ),
        migrations.RenameIndex(
            model_name='staffdailyrollup',
            new_name='tracker_v2__org_id_47c279_idx',
            old_name='v2_sdr_org_day_idx',
        ),
        migrations.RenameIndex(
            model_name='staffdailyrollup',
            new_name='tracker_v2__org_id_c321b2_idx',
            old_name='v2_sdr_org_usr_day_idx',
        ),
        migrations.RenameIndex(
            model_name='wipsnapshot',
            new_name='tracker_v2__org_id_fbba72_idx',
            old_name='v2_wip_org_capt_idx',
        ),
        migrations.AddField(
            model_name='rawevent',
            name='agent_version',
            field=models.CharField(blank=True, db_index=True, help_text="Agent app version that produced this event (e.g. '1.3.24')", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientdailyrollup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='insightdismissal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staffdailyrollup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wipsnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
