# Generated by Django 5.0.6 on 2026-06-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0114_rename_v2_cdr_org_day_idx_tracker_v2__org_id_1ec4a4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Primary contact email pulled from QB/Xero. Used for domain-alias derivation.', max_length=254),
        ),
    ]
