# Generated by Django 5.0.6 on 2026-06-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0115_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawevent',
            name='inference',
            field=models.JSONField(blank=True, default=dict, help_text='Agent inference output: structured client recognition result with confidence, evidence trail, and decay metadata. Populated by agent v1.4+. Empty dict for events from older agents.'),
        ),
    ]
