# Generated by Django 5.0.6 on 2026-06-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0116_rawevent_inference'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='route_individual_returns_to_internal_tax',
            field=models.BooleanField(default=False, help_text="When True, Stage 2 routes individual tax returns (1040, 1041) to this org's 'Internal - Tax' client instead of leaving them unassigned. Enable for firms that bill individual returns as internal firm time. Disable for firms that handle taxpayer billing separately."),
        ),
    ]
