# Generated by Django 5.0.6 on 2026-06-20 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0117_organization_route_individual_returns_to_internal_tax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgroutingrule',
            name='runs_at',
            field=models.CharField(choices=[('agent', 'Agent (live, on-device)'), ('classifier', 'Classifier (server, real-time)'), ('both', 'Agent + Classifier (default for routing rules)'), ('compaction', 'Compaction (server, hourly)'), ('post_save', 'Post-save (server, after write)')], default='agent', help_text='Which engine stage evaluates this rule.', max_length=20),
        ),
        migrations.CreateModel(
            name='RuleSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display label, e.g. 'Outlook.Exe — Inbox'", max_length=255)),
                ('app_hint', models.CharField(blank=True, default='', max_length=255)),
                ('title_hint', models.CharField(blank=True, default='', max_length=255)),
                ('minutes', models.IntegerField(default=0)),
                ('block_count', models.IntegerField(default=0)),
                ('user_count', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, default='', help_text='Optional free-text from the submitter.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_suggestions', to='tracker.organization')),
                ('resulting_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_suggestions', to='tracker.orgroutingrule')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_suggestions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_suggestions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org', 'status'], name='tracker_rul_org_id_c5abd8_idx')],
            },
        ),
    ]
