# Generated by Django 5.0.6 on 2026-06-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0118_alter_orgroutingrule_runs_at_rulesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='ai_attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='block',
            name='ai_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
