# Generated by Django 5.0.6 on 2026-06-29 18:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0120_supportconversation_supportdoc_supportmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportdoc',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
