# Generated by Django 5.0.6 on 2026-07-05 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0121_alter_supportdoc_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='MismatchFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_client_id', models.IntegerField(blank=True, null=True)),
                ('title_client_name', models.CharField(blank=True, max_length=255)),
                ('bucket', models.CharField(default='client', max_length=16)),
                ('match_score', models.FloatField(default=0.0)),
                ('window_title', models.CharField(blank=True, max_length=512)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_reason', models.CharField(blank=True, max_length=64)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mismatch_flags', to='tracker.block')),
                ('booked_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tracker.client')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mismatch_flags', to='tracker.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'resolved_at'], name='tracker_mis_org_id_67e951_idx'), models.Index(fields=['block'], name='tracker_mis_block_i_c46775_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mismatchflag',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('block',), name='uniq_open_mismatch_flag_per_block'),
        ),
    ]
