# Generated by Django 5.0.6 on 2026-07-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0122_mismatchflag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgReportPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rows_axis', models.CharField(choices=[('employee', 'Employee'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], default='employee', max_length=16)),
                ('metric', models.CharField(choices=[('total', 'Total hours'), ('billable', 'Billable hours'), ('non_billable', 'Non-billable hours')], default='billable', max_length=16)),
                ('expand_all', models.BooleanField(default=False)),
                ('paginate', models.BooleanField(default=True)),
                ('show_totals', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_presets', to='tracker.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'is_default'], name='tracker_org_org_id_d63dcc_idx')],
                'unique_together': {('org', 'name')},
            },
        ),
    ]
