# Generated by Django 5.0.6 on 2026-07-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0126_client_alias_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_confirm_client_attributions',
            field=models.BooleanField(default=False, help_text="Broader than auto_confirm_name_matches: auto-confirm (commit) ANY proposed block that is already attributed to a single client with no competing client — even when the evidence is contextual (temporal / co-open / agent) rather than a literal name in the title. This is the 'if it's already under a client, just confirm it' rule (e.g. 'Bank Statements - File Explorer' grouped under a church whose QuickBooks was open). Same safety rails: blocks flagged needs_review still surface, and same-family collisions are held back because a competing client trips the contradiction guard. Preserves each block's billable judgment. Enable per-org only once attribution accuracy is trusted."),
        ),
    ]
