# Generated by Django 5.0.6 on 2026-08-10 19:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0136_capacity_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtier',
            name='bill_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard hourly BILL rate for this tier (what the client is charged). Used as a revenue fallback when a block/client has no explicit rate, before the org default. Null → use org billing_rate_default.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costtier',
            name='hours_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Available working hours per week for this tier (capacity). Drives capacity-based utilization. Null → use org capacity_hours_per_week.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='capacity_hours_per_week',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Available working hours per week per employee (firm-wide default). Denominator for capacity-based utilization = billable ÷ available. Overridden per tier by CostTier.hours_per_week.', max_digits=5),
        ),
    ]
