# Generated by Django 5.0.6 on 2026-08-19 20:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0145_clientbillingprofile_billable_utilization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='relieving_invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice that took this block out of WIP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relieved_blocks', to='tracker.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wip_relief_mode',
            field=models.CharField(blank=True, choices=[('amount', 'FIFO to invoice amount (hourly)'), ('period', 'Whole period (flat fee / retainer)')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wip_relief_residual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Invoice amount minus WIP relieved. Positive = billed more than the time on file (premium/uncaptured time). Negative = wrote down WIP.', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wip_relieved_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Standard-rate value of the WIP blocks this invoice relieved.', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wip_relieved_at',
            field=models.DateTimeField(blank=True, help_text='When this invoice was applied against WIP. Set → never re-applied.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='wip_auto_relief',
            field=models.BooleanField(default=False, help_text="Nightly, apply synced invoices against uninvoiced WIP so WIP drains as the firm bills (services/wip_relief.py). Off until the firm's invoice feed is trusted — run the relieve_wip command dry first."),
        ),
        migrations.AddField(
            model_name='wipsnapshot',
            name='unreviewed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_type', models.CharField(choices=[('tax_return', 'Tax return'), ('bookkeeping', 'Bookkeeping / close'), ('payroll', 'Payroll'), ('advisory', 'Advisory'), ('other', 'Other')], default='other', max_length=20)),
                ('return_type', models.CharField(blank=True, default='', help_text='Tax return form, e.g. "1040", "1120S". Blank for non-tax work.', max_length=16)),
                ('period_label', models.CharField(max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('budget_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_source', models.CharField(choices=[('prior_year', 'Prior-year actual'), ('comparable', 'Median of comparable engagements'), ('manual', 'Set by the firm'), ('none', 'No budget yet')], default='none', max_length=20)),
                ('budget_basis', models.CharField(blank=True, default='', help_text='How the budget was derived, e.g. "TY2024 actual: 12.4h across 31 blocks".', max_length=200)),
                ('budget_set_at', models.DateTimeField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, default='', help_text="Current phase key from the type's PHASE_LADDERS.", max_length=20)),
                ('phase_source', models.CharField(blank=True, choices=[('user', 'Set by the preparer'), ('inferred', 'Inferred from captured activity')], default='', max_length=10)),
                ('phase_set_at', models.DateTimeField(blank=True, null=True)),
                ('inferred_phase', models.CharField(blank=True, default='', max_length=20)),
                ('inferred_phase_confidence', models.FloatField(blank=True, null=True)),
                ('inferred_phase_at', models.DateTimeField(blank=True, null=True)),
                ('inferred_phase_signals', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Delivered'), ('written_off', 'Written off')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='tracker.client')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='tracker.organization')),
                ('phase_set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_phase_updates', to=settings.AUTH_USER_MODEL)),
                ('taxpayer_bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='tracker.taxpayerbucket')),
            ],
            options={
                'db_table': 'tracker_engagement',
                'ordering': ['-period_end', 'client__name'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='engagement',
            field=models.ForeignKey(blank=True, help_text='Engagement this block rolls up to, for budget vs actual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='tracker.engagement'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['org', 'status'], name='tracker_eng_org_id_07737d_idx'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['org', 'client', 'period_label'], name='tracker_eng_org_id_10c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['org', 'engagement_type', 'return_type'], name='tracker_eng_org_id_f9db86_idx'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(fields=('org', 'client', 'taxpayer_bucket', 'engagement_type', 'return_type', 'period_label'), name='uniq_engagement_per_period'),
        ),
    ]
