# Generated by Django 5.0.6 on 2026-08-20 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0148_block_clio_activity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QBVendorClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(db_index=True, help_text='Vendor/customer/employee name as QuickBooks shows it in the window title bracket.', max_length=200)),
                ('company_name', models.CharField(blank=True, default='', help_text='The ambiguous QuickBooks company name this vendor was seen under, for context when reviewing.', max_length=255)),
                ('source', models.CharField(default='group', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='qbvendorclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb_vendors', to='tracker.client'),
        ),
        migrations.AddField(
            model_name='qbvendorclient',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb_vendor_clients', to='tracker.organization'),
        ),
        migrations.AddIndex(
            model_name='qbvendorclient',
            index=models.Index(fields=['org', 'vendor'], name='tracker_qbv_org_id_8c4af3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qbvendorclient',
            unique_together={('org', 'vendor')},
        ),
    ]
