# Generated by Django 5.0.6 on 2026-08-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0155_reconcile_matter_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='clio_push_trigger',
            field=models.CharField(choices=[('approve', 'When a manager approves the timesheet'), ('submit', 'As soon as the person submits it'), ('continuous', 'Nightly, once time has settled — no timesheet needed')], default='approve', help_text='When captured time is written to Clio. "approve" keeps manager review as the gate on what reaches the billing system; "continuous" drops the timesheet entirely and pushes settled, confirmed time on a nightly schedule.', max_length=16),
        ),
    ]
