# Generated by Django 5.0.6 on 2026-09-08 18:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0158_settled_submit_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payroll_burden_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier applied to every cost rate to turn a raw wage into a loaded cost — payroll taxes, benefits, PTO, occupancy. 1.00 means the rates you entered are already fully loaded. Firms typically run 1.15-1.40; at 1.25 a $25/hr wage costs the firm $31.25/hr.', max_digits=4),
        ),
    ]
