# Generated by Django 5.0.6 on 2026-09-09 20:50

from django.db import migrations, models


def turn_on_for_existing(apps, schema_editor):
    """Changing a Django default only affects rows created afterwards.

    Every org already in the database was created under default=False and would
    keep a WIP figure that only ever grows — which is exactly the state this
    change exists to end. Support can still switch an individual org back off.
    """
    apps.get_model("tracker", "Organization").objects.update(wip_auto_relief=True)


def noop(apps, schema_editor):
    """Reversing the field default is enough; we don't guess which orgs were
    deliberately off before."""


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0159_organization_payroll_burden_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='wip_auto_relief',
            field=models.BooleanField(default=True, help_text='Match imported invoices against uninvoiced time each night so WIP falls when the firm bills. On by default — a firm has no reason to want a WIP figure that only grows. Support can switch it off for an org whose invoice feed is duplicating or misdated, while `manage.py relieve_wip --org N` is run dry to check it.'),
        ),
        migrations.RunPython(turn_on_for_existing, noop),
    ]
