# Generated by Django 5.0.6 on 2026-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0175_restore_cliowebhook_handshake_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsignal',
            name='cc_recipients',
            field=models.JSONField(blank=True, help_text='Gmail only, owner-only. [{"email": str, "name": str}] from Cc.', null=True),
        ),
        migrations.AddField(
            model_name='mailsignal',
            name='compose_seconds',
            field=models.PositiveIntegerField(blank=True, help_text="Outbound Gmail only: seconds spent contiguously in Gmail before this send, derived from the user's own blocks. NULL = not computed / sent from somewhere we did not capture (e.g. a phone).", null=True),
        ),
        migrations.AddField(
            model_name='mailsignal',
            name='from_address',
            field=models.CharField(blank=True, help_text='Gmail only, owner-only. Sender address from the From header.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mailsignal',
            name='from_name',
            field=models.CharField(blank=True, help_text='Gmail only, owner-only. Sender display name.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailsignal',
            name='subject',
            field=models.TextField(blank=True, help_text='Gmail only, owner-only. Full subject line.', null=True),
        ),
        migrations.AddField(
            model_name='mailsignal',
            name='to_recipients',
            field=models.JSONField(blank=True, help_text='Gmail only, owner-only. [{"email": str, "name": str}] from To.', null=True),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='sync_cursor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='sync_cursor_set_at',
            field=models.DateTimeField(blank=True, help_text='When the last FULL sync established sync_cursor.', null=True),
        ),
    ]
