# Generated by Django 5.0.6 on 2026-10-01 02:53
#
# Additive and nullable: one JSON column on tracker_agentdevice, no backfill,
# no lock beyond a metadata-only ALTER. Prod migrations are applied MANUALLY
# on Render — run this BEFORE merging. AgentKeyAuthentication loads the whole
# AgentDevice row on EVERY agent request, so code deployed without the column
# 500s every desktop agent, not just hello2 and Settings → Devices.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0177_ignored_email_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdevice',
            name='permission_status',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
