# Generated by Django 5.0.6 on 2026-10-02 18:41
#
# Additive: two new tables, nothing existing is altered, and nothing that
# computes time reads either one. Apply right AFTER the deploy goes live: until
# then /api/agent-work/ and /api/agent-presence/ 500 (agents retry next hour),
# and deleting a User, Client, Organization or AgentDevice fails, because the
# delete collector queries these missing tables.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0178_agentdevice_permission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_kind', models.CharField(choices=[('claude_code', 'Claude Code'), ('codex', 'Codex'), ('other', 'Other')], default='other', max_length=32)),
                ('external_session_id', models.CharField(max_length=128)),
                ('model_name', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(choices=[('hook', 'Agent reported itself'), ('local_log', "Desktop agent read the agent's local log"), ('synthetic_input', 'Desktop agent saw synthetic input'), ('process', 'Desktop agent saw the process running')], default='hook', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('turns', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('cache_read_tokens', models.BigIntegerField(default=0)),
                ('cache_write_tokens', models.BigIntegerField(default=0)),
                ('project_path', models.CharField(blank=True, default='', max_length=512)),
                ('client_hint', models.CharField(blank=True, default='', max_length=255)),
                ('client_source', models.CharField(choices=[('explicit', 'Named by the project'), ('none', 'Unassigned')], default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_work_sessions', to='tracker.client')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_work_sessions', to='tracker.agentdevice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_work_sessions', to='tracker.organization')),
                ('user', models.ForeignKey(blank=True, help_text='The person who ran the agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentPresenceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_start', models.DateTimeField()),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('seconds_observed', models.PositiveIntegerField(default=0)),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
                ('remote_session', models.BooleanField(default=False)),
                ('input_monitor', models.CharField(blank=True, default='', max_length=16)),
                ('clicks_real', models.PositiveIntegerField(default=0)),
                ('clicks_synthetic', models.PositiveIntegerField(default=0)),
                ('synthetic_by', models.JSONField(blank=True, default=dict)),
                ('idle_changes', models.PositiveIntegerField(default=0)),
                ('idle_changes_by_app', models.JSONField(blank=True, default=dict)),
                ('processes', models.JSONField(blank=True, default=dict)),
                ('local_sessions', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_presence_samples', to='tracker.agentdevice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_presence_samples', to='tracker.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_presence_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'bucket_start'], name='tracker_age_org_id_674d83_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='agentpresencesample',
            constraint=models.UniqueConstraint(fields=('device', 'bucket_start'), name='uniq_agent_presence_device_hour'),
        ),
        migrations.AddIndex(
            model_name='agentworksession',
            index=models.Index(fields=['org', 'started_at'], name='tracker_age_org_id_dc334d_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentworksession',
            constraint=models.UniqueConstraint(fields=('org', 'agent_kind', 'external_session_id'), name='uniq_agent_work_session'),
        ),
    ]
