# Generated by Django 5.0.6 on 2026-10-02 18:20
#
# Additive: one new table, nothing existing is altered. Prod migrations are
# applied MANUALLY on Render — run this BEFORE merging, or POST/GET
# /api/agent-work/ 500 until it is applied. No other endpoint reads the table.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0178_agentdevice_permission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_kind', models.CharField(choices=[('claude_code', 'Claude Code'), ('codex', 'Codex'), ('other', 'Other')], default='other', max_length=32)),
                ('external_session_id', models.CharField(max_length=128)),
                ('model_name', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('turns', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('cache_read_tokens', models.BigIntegerField(default=0)),
                ('cache_write_tokens', models.BigIntegerField(default=0)),
                ('project_path', models.CharField(blank=True, default='', max_length=512)),
                ('client_hint', models.CharField(blank=True, default='', max_length=255)),
                ('client_source', models.CharField(choices=[('explicit', 'Named by the project'), ('none', 'Unassigned')], default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_work_sessions', to='tracker.client')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_work_sessions', to='tracker.agentdevice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_work_sessions', to='tracker.organization')),
                ('user', models.ForeignKey(blank=True, help_text='The person who ran the agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['org', 'started_at'], name='tracker_age_org_id_dc334d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='agentworksession',
            constraint=models.UniqueConstraint(fields=('org', 'agent_kind', 'external_session_id'), name='uniq_agent_work_session'),
        ),
    ]
