# Generated by Django 5.0.6 on 2026-10-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0179_agent_work_and_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmattermapping',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date from the source system, when it keeps one.', null=True),
        ),
        migrations.AddField(
            model_name='externalmattermapping',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimate from the source system (e.g. QuickBooks Time). Blank when the source keeps none.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='imported_from',
            field=models.CharField(blank=True, choices=[('', 'Manual'), ('quickbooks', 'QuickBooks'), ('xero', 'Xero'), ('clio', 'Clio'), ('qb_time', 'QuickBooks Time')], default='', help_text='Integration source this client was imported from', max_length=20),
        ),
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('quickbooks', 'QuickBooks Online'), ('xero', 'Xero'), ('karbon', 'Karbon'), ('cch_axcess', 'CCH Axcess Practice'), ('clio', 'Clio Manage'), ('qb_time', 'QuickBooks Time')], max_length=50),
        ),
    ]
