# Generated by Django 5.0.6 on 2026-10-02 19:22
#
# Additive: one JSON column with a default on tracker_agentpresencesample, a
# table nothing that computes time reads. Apply right after the deploy goes
# live; until then POST /api/agent-presence/ 500s (agents keep the hour and
# retry), and deleting a User, Organization or AgentDevice fails because the
# delete collector selects every column of this table.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0179_agent_work_and_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpresencesample',
            name='unattended_by_cause',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
