# Generated by Django 5.0.6 on 2026-10-02 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0180_qb_time_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_month', models.DateField(help_text='First day of the month this budget starts applying.')),
                ('monthly_hours', models.DecimalField(decimal_places=2, help_text='Budgeted hours per month from effective_month on. 0 ends the budget.', max_digits=7)),
                ('source', models.CharField(choices=[('manual', 'Set by the firm'), ('qb_time', 'QuickBooks Time estimate'), ('csv', 'Imported from a file')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_budgets', to='tracker.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='tracker.project')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_budget_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_projectbudget',
                'ordering': ['project_id', '-effective_month'],
                'indexes': [models.Index(fields=['org', 'effective_month'], name='tracker_pro_org_id_75d7ed_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectbudget',
            constraint=models.UniqueConstraint(fields=('project', 'effective_month'), name='uniq_project_budget_month'),
        ),
    ]
