# Generated by Django 5.0.6 on 2026-10-02 19:55
#
# Additive: one new table with NO foreign keys, so no delete anywhere can touch
# it. /api/agent/control/ reads it inside a try/except that defaults to ON, so
# there is no unsafe window: before this is applied, agents simply behave as
# they do today. Apply after deploy, at leisure.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0182_project_budgets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPresenceSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('device_pk', models.IntegerField(blank=True, db_index=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='agentpresenceswitch',
            constraint=models.UniqueConstraint(fields=('org_id', 'device_pk'), name='uniq_agent_presence_switch_scope'),
        ),
    ]
