# Generated by Django 5.0.6 on 2026-10-02 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0183_agent_presence_switch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_for', to='tracker.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_currentproject',
            },
        ),
        migrations.CreateModel(
            name='OrgFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('project_switch', 'Switch Project in the desktop ticker')], max_length=40)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='tracker.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_orgfeatureflag',
            },
        ),
        migrations.AddConstraint(
            model_name='orgfeatureflag',
            constraint=models.UniqueConstraint(fields=('org', 'key'), name='uniq_org_feature_flag'),
        ),
    ]
