# Generated by Django 5.0.6 on 2026-10-02 20:20
#
# Additive: two new tables, no foreign keys. Readers treat any error as
# "report off", so before this is applied the report is simply hidden — no
# unsafe window. Apply after deploy, at leisure.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0184_project_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentActivityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(db_index=True)),
                ('sample_id', models.IntegerField(unique=True)),
                ('verdict', models.CharField(choices=[('human', 'It was me / a person'), ('agent', 'It was an agent')], max_length=8)),
                ('reviewed_by_id', models.IntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirmFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(db_index=True)),
                ('key', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='firmfeatureflag',
            constraint=models.UniqueConstraint(fields=('org_id', 'key'), name='uniq_firm_feature_flag'),
        ),
    ]
