# Generated by Django 5.0.6 on 2026-10-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0186_onboarding_console'),
    ]

    operations = [
        migrations.CreateModel(
            name='QbtPushedTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet_id', models.CharField(max_length=64)),
                ('qbt_user_id', models.CharField(max_length=64)),
                ('jobcode_id', models.CharField(max_length=64)),
                ('day', models.DateField()),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('block_ids', models.JSONField(blank=True, default=list)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qbt_pushed_timesheets', to='tracker.integration')),
            ],
            options={
                'indexes': [models.Index(fields=['integration', 'day'], name='tracker_qbt_integra_21110d_idx')],
                'unique_together': {('integration', 'timesheet_id')},
            },
        ),
    ]
