# Generated by Django 5.0.6 on 2026-10-05 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0187_qbt_pushed_timesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('microsoft', 'Microsoft'), ('google', 'Google')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('email_at_link', models.EmailField(blank=True, default='', help_text='The email the provider reported when this link was made', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_nonce', models.CharField(blank=True, default='', max_length=64)),
                ('ticket_issued_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'subject')},
            },
        ),
    ]
