# Generated by Django 5.0.6 on 2026-10-06 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0190_qbt_timesheet_push'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('providers', models.JSONField(default=list)),
                ('sent_to', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('qbo_state', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('qbt_state', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('qbo_connected_at', models.DateTimeField(blank=True, null=True)),
                ('qbt_connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_links', to='tracker.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_links', to='tracker.onboardingproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
