# Generated by Django 5.0.6 on 2026-10-07 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0193_org_email_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('planned_until', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_pauses', to='tracker.agentdevice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_pauses', to='tracker.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_pauses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['org', 'started_at'], name='tracker_tra_org_id_cd5e31_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='trackingpause',
            constraint=models.UniqueConstraint(fields=('device', 'started_at'), name='uniq_tracking_pause_device_start'),
        ),
    ]
