# Generated by Django 5.0.6 on 2026-10-08 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0193_org_email_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='imported_from',
            field=models.CharField(blank=True, choices=[('', 'Manual'), ('quickbooks', 'QuickBooks'), ('xero', 'Xero'), ('clio', 'Clio'), ('qb_time', 'QuickBooks Time'), ('asana', 'Asana')], default='', help_text='Integration source this client was imported from', max_length=20),
        ),
        migrations.CreateModel(
            name='AsanaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_gid', models.CharField(max_length=64)),
                ('at', models.DateTimeField()),
                ('asana_project_gid', models.CharField(blank=True, default='', max_length=64)),
                ('task_gid', models.CharField(blank=True, default='', max_length=64)),
                ('task_name', models.CharField(blank=True, default='', max_length=500)),
                ('kind', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asana_activity', to='tracker.integration')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asana_activity', to='tracker.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asana_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'at'], name='tracker_asa_user_id_624b49_idx')],
                'unique_together': {('integration', 'story_gid')},
            },
        ),
        migrations.CreateModel(
            name='AsanaProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asana_gid', models.CharField(max_length=64)),
                ('asana_name', models.CharField(blank=True, default='', max_length=500)),
                ('archived', models.BooleanField(default=False)),
                ('link_source', models.CharField(blank=True, choices=[('name', 'Matched by name'), ('manual', 'Linked by hand')], default='', max_length=16)),
                ('activity_cursor', models.DateTimeField(blank=True, null=True)),
                ('last_seen_in_source', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asana_projects', to='tracker.integration')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asana_links', to='tracker.project')),
            ],
            options={
                'unique_together': {('integration', 'asana_gid')},
            },
        ),
    ]
