# Generated by Django 5.0.6 on 2026-10-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0195_asana'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectlink',
            name='asana_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectlink',
            name='asana_state',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
