# Generated by Django 5.0.6 on 2026-10-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0197_orgroutingrule_fallback_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='asanaactivity',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asana_activity', to='tracker.client'),
        ),
        migrations.AddField(
            model_name='asanaprojectlink',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asana_links', to='tracker.client'),
        ),
        migrations.AlterField(
            model_name='asanaprojectlink',
            name='link_source',
            field=models.CharField(blank=True, choices=[('name', 'Matched by name'), ('client', 'Client named, project not'), ('manual', 'Linked by hand')], default='', max_length=16),
        ),
    ]
