# Generated by Django 5.0.6 on 2026-10-08 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0198_asana_client_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asanaprojectlink',
            name='asana_team',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='asanaprojectlink',
            name='client_hint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='asanaprojectlink',
            name='link_source',
            field=models.CharField(blank=True, choices=[('name', 'Matched by name'), ('client', 'Client named, project not'), ('ignored', 'Not a client (by hand)'), ('manual', 'Linked by hand')], default='', max_length=16),
        ),
        migrations.CreateModel(
            name='AsanaNameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('ignore', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asana_name_maps', to='tracker.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asana_name_maps', to='tracker.integration')),
            ],
            options={
                'unique_together': {('integration', 'prefix')},
            },
        ),
    ]
