# Generated by Django 5.0.6 on 2026-10-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0199_asana_name_map_and_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='asanaprojectlink',
            name='qbt_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='asanaprojectlink',
            name='link_source',
            field=models.CharField(blank=True, choices=[('field', 'Linked by its QB Time field in Asana'), ('name', 'Matched by name'), ('client', 'Client named, project not'), ('ignored', 'Not a client (by hand)'), ('manual', 'Linked by hand')], default='', max_length=16),
        ),
    ]
