# Generated by Django 5.0.6 on 2026-10-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0200_asana_qbt_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asanaprojectlink',
            name='link_source',
            field=models.CharField(blank=True, choices=[('field', 'Linked by its QB Time field in Asana'), ('name', 'Matched by name'), ('client', 'Client named, project not'), ('ignored', 'Not a client (by hand)'), ('manual', 'Linked by hand'), ('learned', "Learned from the firm's own time entries")], default='', max_length=16),
        ),
    ]
