a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('notifications.py', '.'),
        ('timetracker_gui.py', '.'),
        ('agent_sync_integration.py', '.'),
        ('quick_switcher.py', '.'),
    ],
    hiddenimports=[
        'UserNotifications',
        'Foundation',
        'objc',
        'AppKit',
        'Quartz',
        'rumps',
        'certifi',
        'pynput',
        'pynput.keyboard',
        'pynput.keyboard._darwin',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='TimeTracker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='TimeTracker',
    distpath='dist',
    workpath='build',
)
app = BUNDLE(
    coll,
    name='TimeTracker.app',
    icon=None,
    bundle_identifier='com.mavops.timetracker',
)