"""
Pulse lens — the Monday morning landing view.

Pulse is unique: it doesn't deeply analyze any one dimension; it surfaces
the 3-5 things that changed enough to matter. The "Needs attention" cards
are generated by the insights engine (analytics_v2/insights/engine.py),
not by lens code directly.

Headline tiles for Pulse are scope-aware:
  firm:    Revenue, Realization $, Billable Util, WIP Total
  client:  Revenue, Realization $, Hours, WIP for this client
  staff:   Billable Hours, Total Hours, Utilization, Realization $
"""
from __future__ import annotations

from typing import Optional

from tracker.models import Organization

from ..insights.engine import generate_pulse_insights
from ..types import Scope, Section, TimeRange
from .base import Lens, register_lens
from .helpers import headline_row, kpi_tile


@register_lens("pulse")
class PulseLens(Lens):
    label = "Pulse"
    
    def assemble(self, org, scope, time, compare=None):
        from ..permissions import firm_invoices_here
        invoiceless = not firm_invoices_here(org)
        
        sections: list[Section] = []
        
        # Headline metrics adapt to scope AND invoice presence
        metric_ids = self._headline_metrics_for_scope(scope, invoiceless)
        sections.append(headline_row(metric_ids, org, scope, time, compare,
                                     section_id="headline"))
        
        # Needs attention — pass invoiceless flag down to insight engine
        insights = generate_pulse_insights(org, scope, time, invoiceless=invoiceless)
        if insights:
            from ..types import Section
            insight_section = Section(
                id="needs_attention",
                type="section",
                title="Needs Attention",
                collapsible=False,
                children=insights,
            )
            sections.append(insight_section)
        
        return sections
    
    def _headline_metrics_for_scope(self, scope: Scope, invoiceless: bool = False) -> list[str]:
        if scope.type == "firm":
            if invoiceless:
                # Block-based revenue, no realization (it'd be 0% and misleading).
                # Leakage still works: worked-but-uncommitted billable value.
                return ["revenue", "revenue_leakage",
                        "billable_mix", "wip_total"]
            return ["invoiced_revenue", "realization_dollar",
                    "revenue_leakage", "wip_total"]
        if scope.type == "client":
            if invoiceless:
                return ["revenue", "billable_hours",
                        "billable_mix", "wip_total"]
            return ["invoiced_revenue", "realization_dollar",
                    "billable_hours", "wip_total"]
        if scope.type == "staff":
            return ["billable_hours", "total_hours",
                    "billable_mix", "effective_rate"]
        return ["revenue", "billable_hours", "billable_mix"]