from django.core.management.base import BaseCommand
from tracker.models import Client, Organization


QB_CLIENTS = [
    '100 Maconi Ave, LLC',
    '1001 Services, LLC',
    '200 Elwood Davis Property LLC',
    '201 S. Main Street',
    '266  Services LLC',
    '309 Driscoll Ave LLC',
    '524 Court Street LLC',
    'Account Temps',
    'Advanced Floor Covering Services',
    'Advertising Distribution Services Inc.',
    'All Round Repair & Sales Corp',
    'All Round Transportation',
    'Allen Road Elementary, PTO',
    'Amalgamated Transit Union',
    'American Federation of Teachers #2623 ESM',
    'AMS Models, Inc.',
    'Angels of Clean',
    'Antelmi, Fusco, & Cazzola, Inc',
    'Appraisal & Real Estate Servives',
    'Archion BioMaterial Company, Inc',
    'Arrow Fence Company, Inc',
    'Artist Bullpen LLC',
    'Aspire Dance CNY Booster Club',
    'ASR',
    'Association of Community Publishers',
    'Assumption Church',
    'Atlantic Seafood of Baldwinsville, Inc',
    'B&S Property Rehab LLC',
    'Back on Track Chiropractic',
    'Bakery & Tobacco Workers Local 116',
    'Barados on the Water',
    'Basilica of The Sacred  Heart of Jesus',
    'Bavarian Club Almenrausch.',
    'BC Fitness',
    'Benjamin Essig',
    'Berry Good Dental',
    'BH Enterprises of CNY Corporate',
    'Bill Welsh Foundation',
    'Born Again Used Furniture & Appl',
    'Brewerton Elementary, PTO',
    'Brian Doyle',
    'Brook Hollow Farms, Inc',
    'Brush Brother',
    'C.W. Rich, Inc',
    'CADD Systems, Inc.',
    'Cadrette Enterprises LLC',
    'Cameze LLC',
    'Caring Family Health Nurse Practioner',
    'Carol McGuinness',
    'Central Bark Canine Events LLC',
    'Central New York Cat Coalition',
    "Children's Consortium",
    'Chrisropher Einhart',
    'Christ our Hope Church',
    'Christ our Hope Church-Boonville',
    'Christ our Light Catholic Community',
    'Chuck It Haulers',
    'Church Of  Annunciation',
    'Church of Our Lady of The Rosary',
    'Church of the Holy Family',
    'Ciereck Enterprises, LLC',
    'CJS SEAFOOD llc',
    'Closer Look Home Inspections, Inc',
    'CNY Coin & Silver, Inc.',
    'CNY Complete Contracting LLC',
    'CNY Sandblasting, Inc.',
    'CNY Web Innovations Corp',
    'Colagiovanni, Paul',
    'Communication Workers',
    'Coopers to Go',
    'Countryside Fitness of Central Square',
    'CRB',
    'Crescendo Music',
    'Cutting Edge Decks, Inc',
    'CWR Inc.',
    'Dawn of the New Day Animal Rescue Inc',
    'Dentivia LLC',
    'Dewitt Professional Firefighters Local 27',
    'Divine Mercy  Parish',
    'Double M Property Holdings LLC',
    'Einstein Construction Group, LLC',
    'Ejoy Being Human',
    'ELI Logistics & Transportation Inc',
    'Ellinwood Dental',
    'Elsworth Louise LLC',
    'Elusive Moose Properties, LLC',
    'Empire Winds, Inc',
    'Escape the Estate LLC',
    'Essig Petroleum',
    'Everclean Cleaning LLC',
    'Fabius Indoor Sports Training LLC',
    'Finisher Floor Covering Corp',
    'First Baptist Chruch of Manlius',
    'First Baptist Church of Syracuse',
    'First Presbyterian Church of Salina',
    'Flawless Hardwood Refinishing LLC',
    "Franciscan's in Collaborative Ministry",
    'Franciscan Properties, Inc.',
    'Franciscan Urban, Inc.',
    'Frenemy Studios LLC',
    'Gary Craven',
    'Genesis II Hair Replacment Stuidio',
    'Genesis II Realty LLC',
    'George & Susan Lowe',
    'Give BAck Movement Inc',
    'Glitter Gala Inc',
    'Gotta Dance Performing Arts Studio, LLC',
    'Grace Episcopal Church',
    'Griffiss Park Suites LLC',
    'GS General Resource Corp',
    'H & B Marketing',
    'Harrington Homes of Jamesville Inc',
    'HC Fitness',
    'Holly Corbett, Inc',
    'Holy Family-Vernon',
    'HRR Properties',
    'Huntington Duke LLC',
    'I-Smile Studios, Inc.',
    'I W Construction Inc',
    'Ice Cream Specialties, Inc',
    'Iggy Solutions LLC',
    'Infocus Advisors',
    'Innovation Promotions & Apparel',
    'INSRE, LLC.',
    'Intrigue Experiences LLC',
    'Intrigue X Inc',
    'Inventory Plus, Inc',
    'J & S Construction',
    'J P Mehlek LTD',
    'JAIMECO LLC',
    'James H Michel Estate',
    'Jessic Detor LCSW PLLC',
    'JJN Properties, LTD.',
    'Joseph Murray',
    'Julie Leechalad',
    'JUNG WHA LEE',
    'JV Graphics LLC',
    'K.F.Knudsen & Assiciates, Inc.',
    'KAJAC Development, Inc.',
    'Keegan-Osbelt-Knight Funeral Home, Inc',
    'knu',
    'Krueger Funeral Home Inc',
    'L&S Veneer, Inc',
    'Lake Effect Stks, LLC',
    'Lan-Dev Associates, llc',
    'Landmark Graphics NY Inc',
    'LandS LLC',
    'Lead Electronics Inc',
    'Lecia Ricelli',
    'Linda Hatz',
    'Linda M Vescio Estate',
    'Little League Baseball, Inc',
    'Local 582',
    'Marilyn E Meyers Estate',
    'Mark Clary',
    'Mary Driscoll-Ingraham',
    'Mary Rodman',
    'McCauley, Lewis & Stephanie',
    'Midnight Express Towing',
    'Midnight Logistics Inc',
    "Mike's Painting Service",
    'MK Boutique',
    "Molly's Wish, Inc.",
    'Mr. & Mrs. Alexander Monroe',
    'Mr. Mikes Seafood, Inc.',
    'Music School of CNY , Inc.',
    'N. Syracuse Fire Department',
    'NAS Enterprises of New York, LLC',
    'North Syracuse Cemetery',
    "North Syracuse Volunteer Fire Fighter's A",
    'Northern Lights Auto Svc, Inc.',
    'Northshore Appliance Services',
    'NTR Properties inc',
    'On Demand Delivery Inc',
    'One Louder Inc',
    'Orange Door, LLC',
    'Ormond Entertainment',
    'Our Lady of Hope Church',
    'Our Lady of Pompei Church',
    'Outside Operations, Inc.',
    'Painters Local 31',
    'Painting with a Twist',
    'Palumbo Project Company, Inc',
    'Pastime Athletic Club',
    'PB Pro Transport, Inc.',
    'Pediatric Now Medical Care, LLC',
    'Peter Dugan',
    'Phoenix Band & Colorguard Booster Club In',
    'Pine Plains Cemetery Association',
    'Pioneer Pump Systems, Inc.',
    'Polisses Plant Works',
    'Ponee Up Club',
    'Postal Workers Local 257',
    'Powering Haiti, Inc',
    'Preserve at Autumn Ridge II, llc',
    'Printable Soultions',
    'Prostream Property Services Inc',
    'Pure Body Place, Inc.',
    'QP2 Properties LLC',
    'Quality Assemblies Inc.',
    'R&G Transportation services LLC',
    'RescueLove, Inc',
    'Retailer Flooring Solutions, Inc.',
    'Revelations Abstract Services Inc',
    'Revive Hope and Healing Ministries, Inc',
    'RF Air Services Inc',
    'Rich Walberger',
    'Richard James',
    'Rickers Towing',
    'RJH Consultants',
    'RM Fitness, LLC',
    'Rob Marashian',
    'Rollers Unlimted',
    'Roots Hair LLC',
    'Roxboro Road Middle School Parent Teacher',
    'RWW Contracting Group, Inc.',
    'Sacred Heart- Cicero',
    'Sacred Heart Parish-Rome',
    'Sager Real Estate Inc',
    'Salt City Harvest Farm',
    'Saratoga Tax',
    'Scanlon Allen Group LLC',
    'Sears Contracting',
    'SGB Properties Inc.',
    'Sher & Gene Brown',
    'Shred Solvers, Inc',
    "Shuster's Flooring",
    'Situational Homes Corp',
    'Slavic Tile Inc',
    'Snack Bear Vending',
    'SNS Remodeling LLC',
    'South Shore Association of Oneida Lake',
    'Sovring-Zutant, Inc.',
    'Spierit Imaging Services.',
    'Spierit Management Services',
    'Spirit and Truth Distibution Center',
    'Spirit of Hope Catholic Comm',
    'Spotless Credit Solutions Inc',
    'SRG One LLC',
    'SRS Systems, Inc',
    "St Anne's Food Pantry",
    'St John Cemetery-Rome',
    "St Leo's & St Ann's Church",
    'St Margarets Church-Homer',
    "St Mary's Church- Clinton",
    "St Mary's Oswego",
    "St Patrick's Church-Jordan",
    "St Patrick's Jordan Cemetery",
    "St Patrick's Taberg",
    "St Peter's Cemetery",
    'St, John the Evangelist',
    "St, Mary's of the Assumption",
    "St. Agatha's Church",
    'St. Anne Mother of Mary Church',
    "St. Charles-St.Ann's Church",
    'St. Francis of Assisi Church',
    'St. Francis Xavier Church',
    "St. Helena's Church- Sherrill",
    "St. John's Church",
    "St. John's Episcopal Church",
    'St. John the Baptist Church',
    "St. Joseph's Church",
    "St. Joseph's Church-Oriskany falls",
    'St. Malachy Church',
    'St. Marks Church',
    "St. Mary's Church-Hamilton",
    "St. Mary's Church-Minoa",
    "St. Mary's of the Lake",
    'St. Matthews Church',
    "St. Paul's Catholic Church",
    'St. Peters Church',
    "St. Theresa's Church",
    'Starlight MFG Solutions LLC',
    'STAT Courier',
    'Stropp Appraisal',
    'Sunshine Treats & Eats',
    'Susan Smith',
    'Syracuse Fire Department Assoc Supplement',
    'Syracuse Fire Dept. Assoc.,Inc',
    'Syracuse Firefighters Assoc Local 280',
    'Syracuse Fitness LLC',
    'Syracuse Gay & Lesbiabn Chorus Inc',
    'Syracuse Realty Group, LLC',
    'T&S Enterprises of CNY, Inc.',
    'T.T. Mitchell Consulting',
    'Terry Horst Landscape Architecture',
    'The Artist Bullpen',
    'The Collateral Collector',
    'The Friary',
    'TJ Erin Corporation',
    'TK Realty Services LLC',
    'TK Realty Services LLC.',
    'TM Lebarv LLC',
    'TMC Transit inc',
    'Transfiguration Church-Rome',
    'Transfiguration Church-Syracuse',
    'Tully United Community Church',
    'Upstate Alternative Energy Inc',
    'USA Needle',
    'Vick & Pathfinder Camp and Conference Min',
    'Victory Bible Church',
    'Victory Development Management',
    'Wealth Max Pro LLC',
    'Wellness Therapy Services LCSW PLLC',
    'Wgner Construction and Property Man',
    'WJ Bos LLC',
    'Z-Loupes, Inc',
    'Internal \u2013 Tax',  # Internal – Tax
]


class Command(BaseCommand):
    help = 'Import TL Wall QB clients and create UltraTax rule'

    def handle(self, *args, **options):
        try:
            org = Organization.objects.get(name__icontains='TL Wall')
        except Organization.DoesNotExist:
            self.stdout.write(self.style.ERROR('TL Wall org not found'))
            return

        existing = set(Client.objects.filter(org=org).values_list('name', flat=True))
        self.stdout.write(f'Existing clients: {len(existing)}')

        created = 0
        skipped = 0

        for name in QB_CLIENTS:
            if name in existing:
                skipped += 1
                continue

            # Generate unique code from initials
            words = [w for w in name.upper().replace(',', '').replace('.', '').split() if w and w[0].isalpha()]
            code = ''.join(w[0] for w in words[:4])[:10]
            base = code
            i = 2
            while Client.objects.filter(org=org, code=code).exists():
                code = f"{base}{i}"
                i += 1

            Client.objects.create(
                org=org,
                name=name,
                code=code,
                aliases=[],
                is_active=True,
            )
            self.stdout.write(f'  + {name} ({code})')
            created += 1

        self.stdout.write(self.style.SUCCESS(
            f'\nDone! Created: {created} | Skipped (existing): {skipped} | '
            f'Total: {Client.objects.filter(org=org).count()}'
        ))